In [1]:
import pandas as pd
import numpy as np
from nsepy import get_history,get_index_pe_history
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
start = dt.datetime(2015,1,1)

end = dt.datetime(2016,1,1)

infy = get_history(symbol='INFY', start = start, end = end)
infy.index = pd.to_datetime(infy.index)
infy.head(10)

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2015-01-01,INFY,EQ,1972.55,1968.95,1982.00,1956.90,1971.00,1974.40,1971.34,500691,9.870306e+13,14908,258080,0.5154
2015-01-02,INFY,EQ,1974.40,1972.00,2019.05,1972.00,2017.95,2013.20,2003.25,1694580,3.394669e+14,54166,1249104,0.7371
2015-01-05,INFY,EQ,2013.20,2009.90,2030.00,1977.50,1996.00,1995.90,2004.59,2484256,4.979911e+14,82694,1830962,0.7370
2015-01-06,INFY,EQ,1995.90,1980.00,1985.00,1934.10,1965.10,1954.20,1954.82,2416829,4.724458e+14,108209,1772070,0.7332
2015-01-07,INFY,EQ,1954.20,1965.00,1974.75,1950.00,1966.05,1963.55,1962.59,1812479,3.557162e+14,62463,1317720,0.7270
2015-01-08,INFY,EQ,1963.55,1985.60,1997.00,1950.00,1979.25,1973.45,1972.78,3391230,6.690160e+14,92752,2686012,0.7920
2015-01-09,INFY,EQ,1973.45,1980.10,2109.00,1913.05,2075.30,2074.45,2037.69,11215832,2.285439e+15,359214,3369489,0.3004
2015-01-12,INFY,EQ,2074.45,2092.00,2119.20,2075.00,2112.95,2115.95,2099.40,3189722,6.696516e+14,107209,1818800,0.5702
2015-01-13,INFY,EQ,2115.95,2107.80,2107.80,2075.00,2092.00,2088.90,2089.42,2200309,4.597374e+14,66676,1385009,0.6295
2015-01-14,INFY,EQ,2088.90,2098.50,2133.00,2092.60,2129.00,2128.65,2110.88,2480315,5.235638e+14,53263,1832958,0.7390

In [3]:
new_infy=infy.reset_index()

In [4]:
new_infy['Date']=pd.to_datetime(new_infy['Date'])
new_infy.head()

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2015-01-01,INFY,EQ,1972.55,1968.95,1982.00,1956.9,1971.00,1974.40,1971.34,500691,9.870306e+13,14908,258080,0.5154
1,2015-01-02,INFY,EQ,1974.40,1972.00,2019.05,1972.0,2017.95,2013.20,2003.25,1694580,3.394669e+14,54166,1249104,0.7371
2,2015-01-05,INFY,EQ,2013.20,2009.90,2030.00,1977.5,1996.00,1995.90,2004.59,2484256,4.979911e+14,82694,1830962,0.7370
3,2015-01-06,INFY,EQ,1995.90,1980.00,1985.00,1934.1,1965.10,1954.20,1954.82,2416829,4.724458e+14,108209,1772070,0.7332
4,2015-01-07,INFY,EQ,1954.20,1965.00,1974.75,1950.0,1966.05,1963.55,1962.59,1812479,3.557162e+14,62463,1317720,0.7270

In [5]:
#moving average
def SMA(data, ndays): 
 SMA = pd.Series((data['Close']).rolling(window=ndays).mean(),name = 'SMA')
 data = data.join(SMA) 
 return data

In [6]:
#moving average for 4 weeks - if there are 5 working days, then n = 20
SMA(new_infy, 20)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,SMA
0,2015-01-01,INFY,EQ,1972.55,1968.95,1982.00,1956.90,1971.00,1974.40,1971.34,500691,9.870306e+13,14908,258080,0.5154,NaN
1,2015-01-02,INFY,EQ,1974.40,1972.00,2019.05,1972.00,2017.95,2013.20,2003.25,1694580,3.394669e+14,54166,1249104,0.7371,NaN
2,2015-01-05,INFY,EQ,2013.20,2009.90,2030.00,1977.50,1996.00,1995.90,2004.59,2484256,4.979911e+14,82694,1830962,0.7370,NaN
3,2015-01-06,INFY,EQ,1995.90,1980.00,1985.00,1934.10,1965.10,1954.20,1954.82,2416829,4.724458e+14,108209,1772070,0.7332,NaN
4,2015-01-07,INFY,EQ,1954.20,1965.00,1974.75,1950.00,1966.05,1963.55,1962.59,1812479,3.557162e+14,62463,1317720,0.7270,NaN
5,2015-01-08,INFY,EQ,1963.55,1985.60,1997.00,1950.00,1979.25,1973.45,1972.78,3391230,6.690160e+14,92752,2686012,0.7920,NaN
6,2015-01-09,INFY,EQ,1973.45,1980.10,2109.00,1913.05,2075.30,2074.45,2037.69,11215832,2.285439e+15,359214,3369489,0.3004,NaN
7,2015-01-12,INFY,EQ,2074.45,2092.00,2119.20,2075.00,2112.95,2115.95,2099.40,3189722,6.696516e+14,107209,1818800,0.5702,NaN
8,2015-01-13,INFY,EQ,2115.95,2107.80,2107.80,2075.00,2092.00,2088.90,2089.42,2200309,4.597374e+14,66676,1385009,0.6295,NaN
9,2015-01-14,INFY,EQ,2088.90,2098.50,2133.00,2092.60,2129.00,2128.65,2110.88,2480315,5.235638e+14,53263,1832958,0.7390,NaN
10,2015-01-15,INFY,EQ,2128.65,2135.20,2152.80,2112.25,2130.00,2134.25,2137.46,2085613,4.457911e+14,48882,1410992,0.6765,NaN
11,2015-01-16,INFY,EQ,2134.25,2148.00,2160.00,2112.00,2115.00,2118.30,2125.77,1672740,3.555858e+14,63848,1254004,0.7497,NaN
12,2015-01-19,INFY,EQ,2118.30,2120.00,2132.35,2094.60,2105.00,2102.50,2104.55,1021936,2.150713e+14,62963,673948,0.6595,NaN
13,2015-01-20,INFY,EQ,2102.50,2107.00,2133.00,2101.45,2119.20,2124.20,2118.16,1701126,3.603258e+14,66871,1284137,0.7549,NaN
14,2015-01-21,INFY,EQ,2124.20,2131.50,2175.95,2118.00,2172.00,2169.90,2148.41,2123727,4.562628e+14,82679,1394125,0.6565,NaN
15,2015-01-22,INFY,EQ,2169.90,2174.80,2203.00,2161.30,2194.95,2196.45,2193.10,2489599,5.459951e+14,82961,1879561,0.7550,NaN
16,2015-01-23,INFY,EQ,2196.45,2200.00,2225.00,2165.10,2211.90,2215.05,2194.58,2371582,5.204624e+14,78929,1622130,0.6840,NaN
17,2015-01-27,INFY,EQ,2215.05,2221.00,2221.00,2130.10,2137.55,2136.50,2146.45,3434992,7.373022e+14,117167,2765575,0.8051,NaN
18,2015-01-28,INFY,EQ,2136.50,2150.00,2154.80,2130.30,2144.45,2144.55,2144.31,3283589,7.041041e+14,99134,2313485,0.7046,NaN
19,2015-01-29,INFY,EQ,2144.55,2145.00,2149.90,2127.60,2147.80,2145.50,2141.67,3842356,8.229076e+14,79209,2797911,0.7282,2088.4925
20,2015-01-30,INFY,EQ,2145.50,2161.50,2162.55,2126.95,2141.85,2141.90,2144.44,2708436,5.808066e+14,99180,2093132,0.7728,2096.8675
21,2015-02-02,INFY,EQ,2141.90,2141.50,2152.00,2126.05,2137.00,2136.85,2142.80,2175635,4.661958e+14,47871,1641719,0.7546,2103.0500
22,2015-02-03,INFY,EQ,2136.85,2136.85,2139.95,2102.00,2124.00,2120.90,2117.92,1316489,2.788217e+14,64490,821456,0.6240,2109.3000
23,2015-02-04,INFY,EQ,2120.90,2139.90,2150.00,2126.40,2143.80,2142.85,2142.92,1290004,2.764378e+14,49317,889211,0.6893,2118.7325
24,2015-02-05,INFY,EQ,2142.85,2150.80,2220.00,2148.00,2186.00,2193.80,2189.61,2968984,6.500912e+14,112707,2025011,0.6821,2130.2450
25,2015-02-06,INFY,EQ,2193.80,2205.00,2247.80,2188.50,2228.00,2230.50,2229.51,1863432,4.154534e+14,79072,1073921,0.5763,2143.0975
26,2015-02-09,INFY,EQ,2230.50,2200.00,2254.00,2200.00,2245.00,2248.90,2238.75,1634217,3.658597e+14,96994,1074815,0.6577,2151.8200
27,2015-02-10,INFY,EQ,2248.90,2243.00,2298.00,2241.00,2268.00,2278.30,2270.89,2129230,4.835242e+14,84805,1385146,0.6505,2159.9375
28,2015-02-11,INFY,EQ,2278.30,2280.50,2293.20,2256.25,2287.80,2284.85,2279.82,1449243,3.304009e+14,58510,962023,0.6638,2169.7350
29,2015-02-12,INFY,EQ,2284.85,2283.00,2321.95,2273.00,2309.90,2311.20,2301.63,1571884,3.617897e+14,66827,995751,0.6335,2178.8625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2015-11-19,INFY,EQ,1020.00,1030.25,1052.00,1023.80,1048.00,1047.80,1038.56,4269811,4.434439e+14,169433,2638720,0.6180,1117.7300
220,2015-11-20,INFY,EQ,1047.80,1048.00,1063.20,1042.05,1051.00,1052.40,1053.83,3041489,3.205220e+14,151348,1851747,0.6088,1113.4300
221,2015-11-23,INFY,EQ,1052.40,1050.00,1062.40,1038.00,1052.00,1053.70,1053.76,2808175,2.959156e+14,90521,1799534,0.6408,1108.6200
222,2015-11-24,INFY,EQ,1053.70,1050.00,1050.80,1037.00,1040.70,1041.15,1043.40,2162901,2.256779e+14,58310,1249010,0.5775,1103.0700
223,2015-11-26,INFY,EQ,1041.15,1040.95,1059.50,1040.05,1050.00,1052.40,1051.79,4926984,5.182137e+14,114757,3656974,0.7422,1098.2200
224,2015-11-27,INFY,EQ,1052.40,1058.00,1070.00,1045.00,1066.00,1066.35,1060.99,2571239,2.728063e+14,69214,1799884,0.7000,1093.8775
225,2015-11-30,INFY,EQ,1066.35,1070.00,1098.30,1056.20,1083.05,1087.90,1083.44,9052767,9.808155e+14,108763,5565189,0.6148,1091.0200
226,2015-12-01,INFY,EQ,1087.90,1088.00,1095.00,1072.95,1075.45,1079.00,1082.42,2949275,3.192357e+14,76585,1982960,0.6724,1088.1975
227,2015-12-02,INFY,EQ,1079.00,1079.95,1079.95,1059.00,1061.10,1060.70,1064.12,3198808,3.403929e+14,90123,2139233,0.6688,1084.6725
228,2015-12-03,INFY,EQ,1060.70,1061.00,1064.80,1049.05,1059.00,1057.75,1056.77,2752363,2.908624e+14,110543,1838358,0.6679,1080.2850
229,2015-12-04,INFY,EQ,1057.75,1049.00,1064.90,1040.10,1048.85,1049.05,1047.32,4187765,4.385928e+14,209805,3031773,0.7240,1075.8975
230,2015-12-07,INFY,EQ,1049.05,1055.30,1059.00,1040.00,1046.00,1046.25,1048.08,2256935,2.365448e+14,65005,1441112,0.6385,1072.0650
231,2015-12-08,INFY,EQ,1046.25,1045.05,1062.75,1039.30,1042.00,1044.40,1051.88,2862186,3.010684e+14,87394,1790175,0.6255,1067.3700
232,2015-12-09,INFY,EQ,1044.40,1043.00,1046.95,1022.55,1024.00,1028.20,1036.19,3409127,3.532487e+14,85433,2068578,0.6068,1062.0500
233,2015-12-10,INFY,EQ,1028.20,1036.60,1051.60,1030.30,1049.90,1047.35,1040.47,2793873,2.906945e+14,80028,1838589,0.6581,1059.2250
234,2015-12-11,INFY,EQ,1047.35,1054.00,1061.90,1045.90,1055.65,1052.80,1052.88,2695099,2.837607e+14,84930,1623053,0.6022,1056.4850
235,2015-12-14,INFY,EQ,1052.80,1049.50,1073.15,1048.05,1067.50,1069.50,1066.30,2408336,2.568018e+14,104978,1419333,0.5893,1054.9200
236,2015-12-15,INFY,EQ,1069.50,1073.25,1079.10,1058.80,1078.50,1077.55,1071.44,2715904,2.909926e+14,76821,1951187,0.7184,1054.7875
237,2015-12-16,INFY,EQ,1077.55,1083.40,1098.00,1083.40,1094.00,1095.85,1092.86,2747926,3.003094e+14,66894,1988090,0.7235,1056.5050
238,2015-12-17,INFY,EQ,1095.85,1100.00,1109.80,1088.00,1105.50,1107.10,1099.83,2479391,2.726907e+14,87599,1294917,0.5223,1060.8600
239,2015-12-18,INFY,EQ,1107.10,1103.40,1103.40,1079.45,1085.95,1083.15,1086.91,3609910,3.923651e+14,65866,2604590,0.7215,1062.6275
240,2015-12-21,INFY,EQ,1083.15,1077.00,1107.40,1065.95,1107.00,1103.45,1095.68,2165506,2.372707e+14,61692,1223571,0.5650,1065.1800
241,2015-12-22,INFY,EQ,1103.45,1097.45,1097.45,1080.10,1085.00,1083.75,1085.81,2054627,2.230939e+14,51963,1204818,0.5864,1066.6825
242,2015-12-23,INFY,EQ,1083.75,1095.05,1102.50,1087.05,1100.00,1100.85,1097.35,1435464,1.575200e+14,38571,861318,0.6000,1069.6675
243,2015-12-24,INFY,EQ,1100.85,1102.05,1104.45,1090.10,1095.80,1096.35,1095.84,615027,6.739696e+13,20528,294731,0.4792,1071.8650
244,2015-12-28,INFY,EQ,1096.35,1090.00,1110.00,1090.00,1103.80,1104.75,1105.51,2763476,3.055046e+14,51103,1880078,0.6803,1073.7850
245,2015-12-29,INFY,EQ,1104.75,1101.25,1110.00,1097.30,1103.00,1104.70,1104.14,1672531,1.846706e+14,52409,967577,0.5785,1074.6250
246,2015-12-30,INFY,EQ,1104.70,1101.10,1106.60,1083.00,1088.00,1086.30,1094.45,2576985,2.820380e+14,65379,1754378,0.6808,1074.9900
247,2015-12-31,INFY,EQ,1086.30,1090.15,1109.95,1087.00,1107.00,1105.40,1102.09,3971969,4.377467e+14,75143,2641827,0.6651,1077.2250
248,2016-01-01,INFY,EQ,1105.40,1100.00,1108.95,1093.20,1103.00,1105.25,1103.13,903275,9.964333e+13,18982,331554,0.3671,1079.6000

In [7]:
#moving average for 16 weeks - if there are 5 working days, then n = 80
SMA(new_infy, 80)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,SMA
0,2015-01-01,INFY,EQ,1972.55,1968.95,1982.00,1956.90,1971.00,1974.40,1971.34,500691,9.870306e+13,14908,258080,0.5154,NaN
1,2015-01-02,INFY,EQ,1974.40,1972.00,2019.05,1972.00,2017.95,2013.20,2003.25,1694580,3.394669e+14,54166,1249104,0.7371,NaN
2,2015-01-05,INFY,EQ,2013.20,2009.90,2030.00,1977.50,1996.00,1995.90,2004.59,2484256,4.979911e+14,82694,1830962,0.7370,NaN
3,2015-01-06,INFY,EQ,1995.90,1980.00,1985.00,1934.10,1965.10,1954.20,1954.82,2416829,4.724458e+14,108209,1772070,0.7332,NaN
4,2015-01-07,INFY,EQ,1954.20,1965.00,1974.75,1950.00,1966.05,1963.55,1962.59,1812479,3.557162e+14,62463,1317720,0.7270,NaN
5,2015-01-08,INFY,EQ,1963.55,1985.60,1997.00,1950.00,1979.25,1973.45,1972.78,3391230,6.690160e+14,92752,2686012,0.7920,NaN
6,2015-01-09,INFY,EQ,1973.45,1980.10,2109.00,1913.05,2075.30,2074.45,2037.69,11215832,2.285439e+15,359214,3369489,0.3004,NaN
7,2015-01-12,INFY,EQ,2074.45,2092.00,2119.20,2075.00,2112.95,2115.95,2099.40,3189722,6.696516e+14,107209,1818800,0.5702,NaN
8,2015-01-13,INFY,EQ,2115.95,2107.80,2107.80,2075.00,2092.00,2088.90,2089.42,2200309,4.597374e+14,66676,1385009,0.6295,NaN
9,2015-01-14,INFY,EQ,2088.90,2098.50,2133.00,2092.60,2129.00,2128.65,2110.88,2480315,5.235638e+14,53263,1832958,0.7390,NaN
10,2015-01-15,INFY,EQ,2128.65,2135.20,2152.80,2112.25,2130.00,2134.25,2137.46,2085613,4.457911e+14,48882,1410992,0.6765,NaN
11,2015-01-16,INFY,EQ,2134.25,2148.00,2160.00,2112.00,2115.00,2118.30,2125.77,1672740,3.555858e+14,63848,1254004,0.7497,NaN
12,2015-01-19,INFY,EQ,2118.30,2120.00,2132.35,2094.60,2105.00,2102.50,2104.55,1021936,2.150713e+14,62963,673948,0.6595,NaN
13,2015-01-20,INFY,EQ,2102.50,2107.00,2133.00,2101.45,2119.20,2124.20,2118.16,1701126,3.603258e+14,66871,1284137,0.7549,NaN
14,2015-01-21,INFY,EQ,2124.20,2131.50,2175.95,2118.00,2172.00,2169.90,2148.41,2123727,4.562628e+14,82679,1394125,0.6565,NaN
15,2015-01-22,INFY,EQ,2169.90,2174.80,2203.00,2161.30,2194.95,2196.45,2193.10,2489599,5.459951e+14,82961,1879561,0.7550,NaN
16,2015-01-23,INFY,EQ,2196.45,2200.00,2225.00,2165.10,2211.90,2215.05,2194.58,2371582,5.204624e+14,78929,1622130,0.6840,NaN
17,2015-01-27,INFY,EQ,2215.05,2221.00,2221.00,2130.10,2137.55,2136.50,2146.45,3434992,7.373022e+14,117167,2765575,0.8051,NaN
18,2015-01-28,INFY,EQ,2136.50,2150.00,2154.80,2130.30,2144.45,2144.55,2144.31,3283589,7.041041e+14,99134,2313485,0.7046,NaN
19,2015-01-29,INFY,EQ,2144.55,2145.00,2149.90,2127.60,2147.80,2145.50,2141.67,3842356,8.229076e+14,79209,2797911,0.7282,NaN
20,2015-01-30,INFY,EQ,2145.50,2161.50,2162.55,2126.95,2141.85,2141.90,2144.44,2708436,5.808066e+14,99180,2093132,0.7728,NaN
21,2015-02-02,INFY,EQ,2141.90,2141.50,2152.00,2126.05,2137.00,2136.85,2142.80,2175635,4.661958e+14,47871,1641719,0.7546,NaN
22,2015-02-03,INFY,EQ,2136.85,2136.85,2139.95,2102.00,2124.00,2120.90,2117.92,1316489,2.788217e+14,64490,821456,0.6240,NaN
23,2015-02-04,INFY,EQ,2120.90,2139.90,2150.00,2126.40,2143.80,2142.85,2142.92,1290004,2.764378e+14,49317,889211,0.6893,NaN
24,2015-02-05,INFY,EQ,2142.85,2150.80,2220.00,2148.00,2186.00,2193.80,2189.61,2968984,6.500912e+14,112707,2025011,0.6821,NaN
25,2015-02-06,INFY,EQ,2193.80,2205.00,2247.80,2188.50,2228.00,2230.50,2229.51,1863432,4.154534e+14,79072,1073921,0.5763,NaN
26,2015-02-09,INFY,EQ,2230.50,2200.00,2254.00,2200.00,2245.00,2248.90,2238.75,1634217,3.658597e+14,96994,1074815,0.6577,NaN
27,2015-02-10,INFY,EQ,2248.90,2243.00,2298.00,2241.00,2268.00,2278.30,2270.89,2129230,4.835242e+14,84805,1385146,0.6505,NaN
28,2015-02-11,INFY,EQ,2278.30,2280.50,2293.20,2256.25,2287.80,2284.85,2279.82,1449243,3.304009e+14,58510,962023,0.6638,NaN
29,2015-02-12,INFY,EQ,2284.85,2283.00,2321.95,2273.00,2309.90,2311.20,2301.63,1571884,3.617897e+14,66827,995751,0.6335,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2015-11-19,INFY,EQ,1020.00,1030.25,1052.00,1023.80,1048.00,1047.80,1038.56,4269811,4.434439e+14,169433,2638720,0.6180,1110.580625
220,2015-11-20,INFY,EQ,1047.80,1048.00,1063.20,1042.05,1051.00,1052.40,1053.83,3041489,3.205220e+14,151348,1851747,0.6088,1110.140625
221,2015-11-23,INFY,EQ,1052.40,1050.00,1062.40,1038.00,1052.00,1053.70,1053.76,2808175,2.959156e+14,90521,1799534,0.6408,1109.995625
222,2015-11-24,INFY,EQ,1053.70,1050.00,1050.80,1037.00,1040.70,1041.15,1043.40,2162901,2.256779e+14,58310,1249010,0.5775,1109.724375
223,2015-11-26,INFY,EQ,1041.15,1040.95,1059.50,1040.05,1050.00,1052.40,1051.79,4926984,5.182137e+14,114757,3656974,0.7422,1109.311875
224,2015-11-27,INFY,EQ,1052.40,1058.00,1070.00,1045.00,1066.00,1066.35,1060.99,2571239,2.728063e+14,69214,1799884,0.7000,1109.266250
225,2015-11-30,INFY,EQ,1066.35,1070.00,1098.30,1056.20,1083.05,1087.90,1083.44,9052767,9.808155e+14,108763,5565189,0.6148,1109.401875
226,2015-12-01,INFY,EQ,1087.90,1088.00,1095.00,1072.95,1075.45,1079.00,1082.42,2949275,3.192357e+14,76585,1982960,0.6724,1109.402500
227,2015-12-02,INFY,EQ,1079.00,1079.95,1079.95,1059.00,1061.10,1060.70,1064.12,3198808,3.403929e+14,90123,2139233,0.6688,1109.445625
228,2015-12-03,INFY,EQ,1060.70,1061.00,1064.80,1049.05,1059.00,1057.75,1056.77,2752363,2.908624e+14,110543,1838358,0.6679,1109.088125
229,2015-12-04,INFY,EQ,1057.75,1049.00,1064.90,1040.10,1048.85,1049.05,1047.32,4187765,4.385928e+14,209805,3031773,0.7240,1108.614375
230,2015-12-07,INFY,EQ,1049.05,1055.30,1059.00,1040.00,1046.00,1046.25,1048.08,2256935,2.365448e+14,65005,1441112,0.6385,1107.997500
231,2015-12-08,INFY,EQ,1046.25,1045.05,1062.75,1039.30,1042.00,1044.40,1051.88,2862186,3.010684e+14,87394,1790175,0.6255,1107.477500
232,2015-12-09,INFY,EQ,1044.40,1043.00,1046.95,1022.55,1024.00,1028.20,1036.19,3409127,3.532487e+14,85433,2068578,0.6068,1106.465625
233,2015-12-10,INFY,EQ,1028.20,1036.60,1051.60,1030.30,1049.90,1047.35,1040.47,2793873,2.906945e+14,80028,1838589,0.6581,1105.252500
234,2015-12-11,INFY,EQ,1047.35,1054.00,1061.90,1045.90,1055.65,1052.80,1052.88,2695099,2.837607e+14,84930,1623053,0.6022,1103.937500
235,2015-12-14,INFY,EQ,1052.80,1049.50,1073.15,1048.05,1067.50,1069.50,1066.30,2408336,2.568018e+14,104978,1419333,0.5893,1102.940625
236,2015-12-15,INFY,EQ,1069.50,1073.25,1079.10,1058.80,1078.50,1077.55,1071.44,2715904,2.909926e+14,76821,1951187,0.7184,1102.133125
237,2015-12-16,INFY,EQ,1077.55,1083.40,1098.00,1083.40,1094.00,1095.85,1092.86,2747926,3.003094e+14,66894,1988090,0.7235,1101.276875
238,2015-12-17,INFY,EQ,1095.85,1100.00,1109.80,1088.00,1105.50,1107.10,1099.83,2479391,2.726907e+14,87599,1294917,0.5223,1100.421250
239,2015-12-18,INFY,EQ,1107.10,1103.40,1103.40,1079.45,1085.95,1083.15,1086.91,3609910,3.923651e+14,65866,2604590,0.7215,1099.778750
240,2015-12-21,INFY,EQ,1083.15,1077.00,1107.40,1065.95,1107.00,1103.45,1095.68,2165506,2.372707e+14,61692,1223571,0.5650,1099.198125
241,2015-12-22,INFY,EQ,1103.45,1097.45,1097.45,1080.10,1085.00,1083.75,1085.81,2054627,2.230939e+14,51963,1204818,0.5864,1099.094375
242,2015-12-23,INFY,EQ,1083.75,1095.05,1102.50,1087.05,1100.00,1100.85,1097.35,1435464,1.575200e+14,38571,861318,0.6000,1099.284375
243,2015-12-24,INFY,EQ,1100.85,1102.05,1104.45,1090.10,1095.80,1096.35,1095.84,615027,6.739696e+13,20528,294731,0.4792,1099.681250
244,2015-12-28,INFY,EQ,1096.35,1090.00,1110.00,1090.00,1103.80,1104.75,1105.51,2763476,3.055046e+14,51103,1880078,0.6803,1099.955625
245,2015-12-29,INFY,EQ,1104.75,1101.25,1110.00,1097.30,1103.00,1104.70,1104.14,1672531,1.846706e+14,52409,967577,0.5785,1099.876250
246,2015-12-30,INFY,EQ,1104.70,1101.10,1106.60,1083.00,1088.00,1086.30,1094.45,2576985,2.820380e+14,65379,1754378,0.6808,1099.775000
247,2015-12-31,INFY,EQ,1086.30,1090.15,1109.95,1087.00,1107.00,1105.40,1102.09,3971969,4.377467e+14,75143,2641827,0.6651,1099.980000
248,2016-01-01,INFY,EQ,1105.40,1100.00,1108.95,1093.20,1103.00,1105.25,1103.13,903275,9.964333e+13,18982,331554,0.3671,1100.052500

In [8]:
#moving average for 52 weeks - if there are 5 working days, then n = 260 but here i ll take n=240 due to data size
SMA(new_infy, 240)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,SMA
0,2015-01-01,INFY,EQ,1972.55,1968.95,1982.00,1956.90,1971.00,1974.40,1971.34,500691,9.870306e+13,14908,258080,0.5154,NaN
1,2015-01-02,INFY,EQ,1974.40,1972.00,2019.05,1972.00,2017.95,2013.20,2003.25,1694580,3.394669e+14,54166,1249104,0.7371,NaN
2,2015-01-05,INFY,EQ,2013.20,2009.90,2030.00,1977.50,1996.00,1995.90,2004.59,2484256,4.979911e+14,82694,1830962,0.7370,NaN
3,2015-01-06,INFY,EQ,1995.90,1980.00,1985.00,1934.10,1965.10,1954.20,1954.82,2416829,4.724458e+14,108209,1772070,0.7332,NaN
4,2015-01-07,INFY,EQ,1954.20,1965.00,1974.75,1950.00,1966.05,1963.55,1962.59,1812479,3.557162e+14,62463,1317720,0.7270,NaN
5,2015-01-08,INFY,EQ,1963.55,1985.60,1997.00,1950.00,1979.25,1973.45,1972.78,3391230,6.690160e+14,92752,2686012,0.7920,NaN
6,2015-01-09,INFY,EQ,1973.45,1980.10,2109.00,1913.05,2075.30,2074.45,2037.69,11215832,2.285439e+15,359214,3369489,0.3004,NaN
7,2015-01-12,INFY,EQ,2074.45,2092.00,2119.20,2075.00,2112.95,2115.95,2099.40,3189722,6.696516e+14,107209,1818800,0.5702,NaN
8,2015-01-13,INFY,EQ,2115.95,2107.80,2107.80,2075.00,2092.00,2088.90,2089.42,2200309,4.597374e+14,66676,1385009,0.6295,NaN
9,2015-01-14,INFY,EQ,2088.90,2098.50,2133.00,2092.60,2129.00,2128.65,2110.88,2480315,5.235638e+14,53263,1832958,0.7390,NaN
10,2015-01-15,INFY,EQ,2128.65,2135.20,2152.80,2112.25,2130.00,2134.25,2137.46,2085613,4.457911e+14,48882,1410992,0.6765,NaN
11,2015-01-16,INFY,EQ,2134.25,2148.00,2160.00,2112.00,2115.00,2118.30,2125.77,1672740,3.555858e+14,63848,1254004,0.7497,NaN
12,2015-01-19,INFY,EQ,2118.30,2120.00,2132.35,2094.60,2105.00,2102.50,2104.55,1021936,2.150713e+14,62963,673948,0.6595,NaN
13,2015-01-20,INFY,EQ,2102.50,2107.00,2133.00,2101.45,2119.20,2124.20,2118.16,1701126,3.603258e+14,66871,1284137,0.7549,NaN
14,2015-01-21,INFY,EQ,2124.20,2131.50,2175.95,2118.00,2172.00,2169.90,2148.41,2123727,4.562628e+14,82679,1394125,0.6565,NaN
15,2015-01-22,INFY,EQ,2169.90,2174.80,2203.00,2161.30,2194.95,2196.45,2193.10,2489599,5.459951e+14,82961,1879561,0.7550,NaN
16,2015-01-23,INFY,EQ,2196.45,2200.00,2225.00,2165.10,2211.90,2215.05,2194.58,2371582,5.204624e+14,78929,1622130,0.6840,NaN
17,2015-01-27,INFY,EQ,2215.05,2221.00,2221.00,2130.10,2137.55,2136.50,2146.45,3434992,7.373022e+14,117167,2765575,0.8051,NaN
18,2015-01-28,INFY,EQ,2136.50,2150.00,2154.80,2130.30,2144.45,2144.55,2144.31,3283589,7.041041e+14,99134,2313485,0.7046,NaN
19,2015-01-29,INFY,EQ,2144.55,2145.00,2149.90,2127.60,2147.80,2145.50,2141.67,3842356,8.229076e+14,79209,2797911,0.7282,NaN
20,2015-01-30,INFY,EQ,2145.50,2161.50,2162.55,2126.95,2141.85,2141.90,2144.44,2708436,5.808066e+14,99180,2093132,0.7728,NaN
21,2015-02-02,INFY,EQ,2141.90,2141.50,2152.00,2126.05,2137.00,2136.85,2142.80,2175635,4.661958e+14,47871,1641719,0.7546,NaN
22,2015-02-03,INFY,EQ,2136.85,2136.85,2139.95,2102.00,2124.00,2120.90,2117.92,1316489,2.788217e+14,64490,821456,0.6240,NaN
23,2015-02-04,INFY,EQ,2120.90,2139.90,2150.00,2126.40,2143.80,2142.85,2142.92,1290004,2.764378e+14,49317,889211,0.6893,NaN
24,2015-02-05,INFY,EQ,2142.85,2150.80,2220.00,2148.00,2186.00,2193.80,2189.61,2968984,6.500912e+14,112707,2025011,0.6821,NaN
25,2015-02-06,INFY,EQ,2193.80,2205.00,2247.80,2188.50,2228.00,2230.50,2229.51,1863432,4.154534e+14,79072,1073921,0.5763,NaN
26,2015-02-09,INFY,EQ,2230.50,2200.00,2254.00,2200.00,2245.00,2248.90,2238.75,1634217,3.658597e+14,96994,1074815,0.6577,NaN
27,2015-02-10,INFY,EQ,2248.90,2243.00,2298.00,2241.00,2268.00,2278.30,2270.89,2129230,4.835242e+14,84805,1385146,0.6505,NaN
28,2015-02-11,INFY,EQ,2278.30,2280.50,2293.20,2256.25,2287.80,2284.85,2279.82,1449243,3.304009e+14,58510,962023,0.6638,NaN
29,2015-02-12,INFY,EQ,2284.85,2283.00,2321.95,2273.00,2309.90,2311.20,2301.63,1571884,3.617897e+14,66827,995751,0.6335,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2015-11-19,INFY,EQ,1020.00,1030.25,1052.00,1023.80,1048.00,1047.80,1038.56,4269811,4.434439e+14,169433,2638720,0.6180,NaN
220,2015-11-20,INFY,EQ,1047.80,1048.00,1063.20,1042.05,1051.00,1052.40,1053.83,3041489,3.205220e+14,151348,1851747,0.6088,NaN
221,2015-11-23,INFY,EQ,1052.40,1050.00,1062.40,1038.00,1052.00,1053.70,1053.76,2808175,2.959156e+14,90521,1799534,0.6408,NaN
222,2015-11-24,INFY,EQ,1053.70,1050.00,1050.80,1037.00,1040.70,1041.15,1043.40,2162901,2.256779e+14,58310,1249010,0.5775,NaN
223,2015-11-26,INFY,EQ,1041.15,1040.95,1059.50,1040.05,1050.00,1052.40,1051.79,4926984,5.182137e+14,114757,3656974,0.7422,NaN
224,2015-11-27,INFY,EQ,1052.40,1058.00,1070.00,1045.00,1066.00,1066.35,1060.99,2571239,2.728063e+14,69214,1799884,0.7000,NaN
225,2015-11-30,INFY,EQ,1066.35,1070.00,1098.30,1056.20,1083.05,1087.90,1083.44,9052767,9.808155e+14,108763,5565189,0.6148,NaN
226,2015-12-01,INFY,EQ,1087.90,1088.00,1095.00,1072.95,1075.45,1079.00,1082.42,2949275,3.192357e+14,76585,1982960,0.6724,NaN
227,2015-12-02,INFY,EQ,1079.00,1079.95,1079.95,1059.00,1061.10,1060.70,1064.12,3198808,3.403929e+14,90123,2139233,0.6688,NaN
228,2015-12-03,INFY,EQ,1060.70,1061.00,1064.80,1049.05,1059.00,1057.75,1056.77,2752363,2.908624e+14,110543,1838358,0.6679,NaN
229,2015-12-04,INFY,EQ,1057.75,1049.00,1064.90,1040.10,1048.85,1049.05,1047.32,4187765,4.385928e+14,209805,3031773,0.7240,NaN
230,2015-12-07,INFY,EQ,1049.05,1055.30,1059.00,1040.00,1046.00,1046.25,1048.08,2256935,2.365448e+14,65005,1441112,0.6385,NaN
231,2015-12-08,INFY,EQ,1046.25,1045.05,1062.75,1039.30,1042.00,1044.40,1051.88,2862186,3.010684e+14,87394,1790175,0.6255,NaN
232,2015-12-09,INFY,EQ,1044.40,1043.00,1046.95,1022.55,1024.00,1028.20,1036.19,3409127,3.532487e+14,85433,2068578,0.6068,NaN
233,2015-12-10,INFY,EQ,1028.20,1036.60,1051.60,1030.30,1049.90,1047.35,1040.47,2793873,2.906945e+14,80028,1838589,0.6581,NaN
234,2015-12-11,INFY,EQ,1047.35,1054.00,1061.90,1045.90,1055.65,1052.80,1052.88,2695099,2.837607e+14,84930,1623053,0.6022,NaN
235,2015-12-14,INFY,EQ,1052.80,1049.50,1073.15,1048.05,1067.50,1069.50,1066.30,2408336,2.568018e+14,104978,1419333,0.5893,NaN
236,2015-12-15,INFY,EQ,1069.50,1073.25,1079.10,1058.80,1078.50,1077.55,1071.44,2715904,2.909926e+14,76821,1951187,0.7184,NaN
237,2015-12-16,INFY,EQ,1077.55,1083.40,1098.00,1083.40,1094.00,1095.85,1092.86,2747926,3.003094e+14,66894,1988090,0.7235,NaN
238,2015-12-17,INFY,EQ,1095.85,1100.00,1109.80,1088.00,1105.50,1107.10,1099.83,2479391,2.726907e+14,87599,1294917,0.5223,NaN
239,2015-12-18,INFY,EQ,1107.10,1103.40,1103.40,1079.45,1085.95,1083.15,1086.91,3609910,3.923651e+14,65866,2604590,0.7215,1562.971042
240,2015-12-21,INFY,EQ,1083.15,1077.00,1107.40,1065.95,1107.00,1103.45,1095.68,2165506,2.372707e+14,61692,1223571,0.5650,1559.342083
241,2015-12-22,INFY,EQ,1103.45,1097.45,1097.45,1080.10,1085.00,1083.75,1085.81,2054627,2.230939e+14,51963,1204818,0.5864,1555.469375
242,2015-12-23,INFY,EQ,1083.75,1095.05,1102.50,1087.05,1100.00,1100.85,1097.35,1435464,1.575200e+14,38571,861318,0.6000,1551.740000
243,2015-12-24,INFY,EQ,1100.85,1102.05,1104.45,1090.10,1095.80,1096.35,1095.84,615027,6.739696e+13,20528,294731,0.4792,1548.165625
244,2015-12-28,INFY,EQ,1096.35,1090.00,1110.00,1090.00,1103.80,1104.75,1105.51,2763476,3.055046e+14,51103,1880078,0.6803,1544.587292
245,2015-12-29,INFY,EQ,1104.75,1101.25,1110.00,1097.30,1103.00,1104.70,1104.14,1672531,1.846706e+14,52409,967577,0.5785,1540.967500
246,2015-12-30,INFY,EQ,1104.70,1101.10,1106.60,1083.00,1088.00,1086.30,1094.45,2576985,2.820380e+14,65379,1754378,0.6808,1536.850208
247,2015-12-31,INFY,EQ,1086.30,1090.15,1109.95,1087.00,1107.00,1105.40,1102.09,3971969,4.377467e+14,75143,2641827,0.6651,1532.639583
248,2016-01-01,INFY,EQ,1105.40,1100.00,1108.95,1093.20,1103.00,1105.25,1103.13,903275,9.964333e+13,18982,331554,0.3671,1528.541042

In [9]:
infydf=pd.DataFrame(new_infy)
infydf.head()

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2015-01-01,INFY,EQ,1972.55,1968.95,1982.00,1956.9,1971.00,1974.40,1971.34,500691,9.870306e+13,14908,258080,0.5154
1,2015-01-02,INFY,EQ,1974.40,1972.00,2019.05,1972.0,2017.95,2013.20,2003.25,1694580,3.394669e+14,54166,1249104,0.7371
2,2015-01-05,INFY,EQ,2013.20,2009.90,2030.00,1977.5,1996.00,1995.90,2004.59,2484256,4.979911e+14,82694,1830962,0.7370
3,2015-01-06,INFY,EQ,1995.90,1980.00,1985.00,1934.1,1965.10,1954.20,1954.82,2416829,4.724458e+14,108209,1772070,0.7332
4,2015-01-07,INFY,EQ,1954.20,1965.00,1974.75,1950.0,1966.05,1963.55,1962.59,1812479,3.557162e+14,62463,1317720,0.7270

In [10]:
vol = infydf['Volume'].index.values.tolist()
volume_shocks =[]
for i in range(1,len(vol)):
    if(infydf['Volume'][i]>(infydf['Volume'][i-1]+(.1*infydf['Volume'][i-1]))):
        volume_shocks.append(1)
    else:
        volume_shocks.append(0)
print(volume_shocks)

[1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0]

In [11]:
infydf['Volume_shocks']=pd.DataFrame({'Volume Shocks':volume_shocks})

In [12]:
infydf.head(10)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Volume_shocks
0,2015-01-01,INFY,EQ,1972.55,1968.95,1982.00,1956.90,1971.00,1974.40,1971.34,500691,9.870306e+13,14908,258080,0.5154,1.0
1,2015-01-02,INFY,EQ,1974.40,1972.00,2019.05,1972.00,2017.95,2013.20,2003.25,1694580,3.394669e+14,54166,1249104,0.7371,1.0
2,2015-01-05,INFY,EQ,2013.20,2009.90,2030.00,1977.50,1996.00,1995.90,2004.59,2484256,4.979911e+14,82694,1830962,0.7370,0.0
3,2015-01-06,INFY,EQ,1995.90,1980.00,1985.00,1934.10,1965.10,1954.20,1954.82,2416829,4.724458e+14,108209,1772070,0.7332,0.0
4,2015-01-07,INFY,EQ,1954.20,1965.00,1974.75,1950.00,1966.05,1963.55,1962.59,1812479,3.557162e+14,62463,1317720,0.7270,1.0
5,2015-01-08,INFY,EQ,1963.55,1985.60,1997.00,1950.00,1979.25,1973.45,1972.78,3391230,6.690160e+14,92752,2686012,0.7920,1.0
6,2015-01-09,INFY,EQ,1973.45,1980.10,2109.00,1913.05,2075.30,2074.45,2037.69,11215832,2.285439e+15,359214,3369489,0.3004,0.0
7,2015-01-12,INFY,EQ,2074.45,2092.00,2119.20,2075.00,2112.95,2115.95,2099.40,3189722,6.696516e+14,107209,1818800,0.5702,0.0
8,2015-01-13,INFY,EQ,2115.95,2107.80,2107.80,2075.00,2092.00,2088.90,2089.42,2200309,4.597374e+14,66676,1385009,0.6295,1.0
9,2015-01-14,INFY,EQ,2088.90,2098.50,2133.00,2092.60,2129.00,2128.65,2110.88,2480315,5.235638e+14,53263,1832958,0.7390,0.0

In [13]:
closing=infydf['Close'].index.tolist()
price_shock=[]
for i in range(0,len(closing)-1):
    if(infydf['Close'][i+1]-infydf['Close'][i]>(.02*(infydf['Close'][i+1]-infydf['Close'][i]))):
        price_shock.append(1)
    else:
        price_shock.append(0)
infydf['Price_shocks']=pd.DataFrame({'Price_shocks':price_shock})
infydf.head(10)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Volume_shocks,Price_shocks
0,2015-01-01,INFY,EQ,1972.55,1968.95,1982.00,1956.90,1971.00,1974.40,1971.34,500691,9.870306e+13,14908,258080,0.5154,1.0,1.0
1,2015-01-02,INFY,EQ,1974.40,1972.00,2019.05,1972.00,2017.95,2013.20,2003.25,1694580,3.394669e+14,54166,1249104,0.7371,1.0,0.0
2,2015-01-05,INFY,EQ,2013.20,2009.90,2030.00,1977.50,1996.00,1995.90,2004.59,2484256,4.979911e+14,82694,1830962,0.7370,0.0,0.0
3,2015-01-06,INFY,EQ,1995.90,1980.00,1985.00,1934.10,1965.10,1954.20,1954.82,2416829,4.724458e+14,108209,1772070,0.7332,0.0,1.0
4,2015-01-07,INFY,EQ,1954.20,1965.00,1974.75,1950.00,1966.05,1963.55,1962.59,1812479,3.557162e+14,62463,1317720,0.7270,1.0,1.0
5,2015-01-08,INFY,EQ,1963.55,1985.60,1997.00,1950.00,1979.25,1973.45,1972.78,3391230,6.690160e+14,92752,2686012,0.7920,1.0,1.0
6,2015-01-09,INFY,EQ,1973.45,1980.10,2109.00,1913.05,2075.30,2074.45,2037.69,11215832,2.285439e+15,359214,3369489,0.3004,0.0,1.0
7,2015-01-12,INFY,EQ,2074.45,2092.00,2119.20,2075.00,2112.95,2115.95,2099.40,3189722,6.696516e+14,107209,1818800,0.5702,0.0,0.0
8,2015-01-13,INFY,EQ,2115.95,2107.80,2107.80,2075.00,2092.00,2088.90,2089.42,2200309,4.597374e+14,66676,1385009,0.6295,1.0,1.0
9,2015-01-14,INFY,EQ,2088.90,2098.50,2133.00,2092.60,2129.00,2128.65,2110.88,2480315,5.235638e+14,53263,1832958,0.7390,0.0,1.0

In [14]:
#model testing

import warnings
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

In [15]:
Infy=infy.drop(columns=['Symbol','Series'])
Infy.head()

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,
2015-01-01,1972.55,1968.95,1982.00,1956.9,1971.00,1974.40,1971.34,500691,9.870306e+13,14908,258080,0.5154
2015-01-02,1974.40,1972.00,2019.05,1972.0,2017.95,2013.20,2003.25,1694580,3.394669e+14,54166,1249104,0.7371
2015-01-05,2013.20,2009.90,2030.00,1977.5,1996.00,1995.90,2004.59,2484256,4.979911e+14,82694,1830962,0.7370
2015-01-06,1995.90,1980.00,1985.00,1934.1,1965.10,1954.20,1954.82,2416829,4.724458e+14,108209,1772070,0.7332
2015-01-07,1954.20,1965.00,1974.75,1950.0,1966.05,1963.55,1962.59,1812479,3.557162e+14,62463,1317720,0.7270

In [16]:
X = Infy.iloc[:, :-1].values
y = Infy.iloc[:, 11].values

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [18]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [19]:
#predict the test set results
y_pred = lr.predict(X_test)
y_pred

array([0.55410456, 0.63414293, 0.44044239, 0.64121092, 0.70309933,
       0.69653961, 0.69154876, 0.66261992, 0.6129678 , 0.63981788,
       0.65874177, 0.61813623, 0.71367135, 0.67315279, 0.73503651,
       0.58297555, 0.67126225, 0.6068351 , 0.7165307 , 0.66640772,
       0.66444982, 0.58793384, 0.74739721, 0.66157507, 0.66221316,
       0.56341449, 0.6446764 , 0.55510938, 0.72774835, 0.68733838,
       0.6919178 , 0.68265953, 0.67985281, 0.71685653, 0.67808832,
       0.77915137, 0.65949372, 0.59696813, 0.65735574, 0.65287541,
       0.59481282, 0.64470626, 0.72470424, 0.55778607, 0.74947957,
       0.71047619, 0.65883103, 0.72933646, 0.77365414, 0.64123017])

In [20]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rmse = sqrt(mean_squared_error(y_test, y_pred))

from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

adj_r2 = 1 - float(len(y)-1)/(len(y)-len(lr.coef_)-1)*(1 - r2)

rmse, r2, adj_r2,  lr.coef_, lr.intercept_

(0.052434498758526814,
 0.7210522756821636,
 0.7081053348910403,
 array([-2.24236139e-05,  2.75315779e-04, -4.85435367e-04,  6.62275186e-04,
         5.70982256e-04, -6.27604684e-04, -3.22130622e-04, -8.64991682e-08,
         7.99599102e-17,  1.19563408e-07,  1.48520981e-07]),
 0.5282399713601063)

In [21]:
from sklearn.linear_model import LassoLars
regressor = LassoLars(alpha=0.01)
regressor.fit(X_train,y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([0.66218794, 0.66218794, 0.66218794, 0.66218794, 0.66218794,
       0.66218794, 0.66218794, 0.66218794, 0.66218794, 0.66218794,
       0.66218794, 0.66218794, 0.66218794, 0.66218794, 0.66218794,
       0.66218794, 0.66218794, 0.66218794, 0.66218794, 0.66218794,
       0.66218794, 0.66218794, 0.66218794, 0.66218794, 0.66218794,
       0.66218794, 0.66218794, 0.66218794, 0.66218794, 0.66218794,
       0.66218794, 0.66218794, 0.66218794, 0.66218794, 0.66218794,
       0.66218794, 0.66218794, 0.66218794, 0.66218794, 0.66218794,
       0.66218794, 0.66218794, 0.66218794, 0.66218794, 0.66218794,
       0.66218794, 0.66218794, 0.66218794, 0.66218794, 0.66218794])

In [22]:
#Applying k-Fold Cross Validation

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=regressor,X=X_train,y=y_train,cv=10)
accuracies

array([-1.39440753e-04, -5.40312936e-05, -3.09539169e-03, -1.76122202e-02,
       -1.09261418e-02, -2.59931426e-03, -4.75332818e-01, -9.99635238e-02,
       -4.86964492e-03, -7.62860596e-02])

In [23]:
#ridge
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [24]:
from sklearn.linear_model import Ridge
regressor = Ridge()
regressor.fit(X_train,y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number6.244986e-29
  overwrite_a=True).T

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [25]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([0.55337637, 0.63555083, 0.46494348, 0.63837675, 0.704009  ,
       0.70402356, 0.6926729 , 0.65228997, 0.60067382, 0.63630545,
       0.65909565, 0.61852002, 0.71756681, 0.67489103, 0.71241343,
       0.58582508, 0.66800778, 0.60905048, 0.70978835, 0.66560793,
       0.66345717, 0.58939613, 0.74210865, 0.66044925, 0.65653416,
       0.56122489, 0.65155123, 0.1213253 , 0.73036057, 0.69147912,
       0.69544771, 0.68017822, 0.67860775, 0.71565237, 0.67350106,
       0.79025081, 0.65817866, 0.59839848, 0.65614528, 0.66260945,
       0.60065117, 0.64338381, 0.72654112, 0.55760981, 0.75591716,
       0.71248426, 0.65929593, 0.73042229, 0.77716221, 0.64254042,
       0.64249589, 0.76263459, 0.65970155, 0.73044068, 0.67134809,
       0.67608243, 0.6459422 , 0.62012106, 0.71415895, 0.64528232,
       0.58676506, 0.62512542, 0.67093781])

In [26]:
#Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=regressor,X=X_train,y=y_train,cv=10)
accuracies

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.860766e-29
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.562434e-29
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number6.052511e-29
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number7.615354e-29
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.904765e-29
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number8.028621e-29
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number6.175159e-29
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.111233e-29
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number6.045870e-29
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number6.042600e-29
  overwrite_a=True).T

array([0.67430156, 0.49235033, 0.66548321, 0.53649158, 0.71418897,
       0.81903693, 0.30697921, 0.60933183, 0.55933844, 0.10322202])

In [46]:
def price_shock_wo_vol_shock(stock):
    
    stock["not_vol_shock"]  = ((stock["Volume_shocks"].astype(bool))).astype(int)
    stock["price_shock_w/0_vol_shock"] = stock["not_vol_shock"] & stock["Price_shocks"]
    
    return stock

In [48]:
price_shock_wo_vol_shock(infydf)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Volume_shocks,Price_shocks,not_vol_shock,price_shock_w/0_vol_shock
0,2015-01-01,INFY,EQ,1972.55,1968.95,1982.00,1956.90,1971.00,1974.40,1971.34,500691,9.870306e+13,14908,258080,0.5154,1.0,1.0,1,True
1,2015-01-02,INFY,EQ,1974.40,1972.00,2019.05,1972.00,2017.95,2013.20,2003.25,1694580,3.394669e+14,54166,1249104,0.7371,1.0,0.0,1,False
2,2015-01-05,INFY,EQ,2013.20,2009.90,2030.00,1977.50,1996.00,1995.90,2004.59,2484256,4.979911e+14,82694,1830962,0.7370,0.0,0.0,0,False
3,2015-01-06,INFY,EQ,1995.90,1980.00,1985.00,1934.10,1965.10,1954.20,1954.82,2416829,4.724458e+14,108209,1772070,0.7332,0.0,1.0,0,False
4,2015-01-07,INFY,EQ,1954.20,1965.00,1974.75,1950.00,1966.05,1963.55,1962.59,1812479,3.557162e+14,62463,1317720,0.7270,1.0,1.0,1,True
5,2015-01-08,INFY,EQ,1963.55,1985.60,1997.00,1950.00,1979.25,1973.45,1972.78,3391230,6.690160e+14,92752,2686012,0.7920,1.0,1.0,1,True
6,2015-01-09,INFY,EQ,1973.45,1980.10,2109.00,1913.05,2075.30,2074.45,2037.69,11215832,2.285439e+15,359214,3369489,0.3004,0.0,1.0,0,False
7,2015-01-12,INFY,EQ,2074.45,2092.00,2119.20,2075.00,2112.95,2115.95,2099.40,3189722,6.696516e+14,107209,1818800,0.5702,0.0,0.0,0,False
8,2015-01-13,INFY,EQ,2115.95,2107.80,2107.80,2075.00,2092.00,2088.90,2089.42,2200309,4.597374e+14,66676,1385009,0.6295,1.0,1.0,1,True
9,2015-01-14,INFY,EQ,2088.90,2098.50,2133.00,2092.60,2129.00,2128.65,2110.88,2480315,5.235638e+14,53263,1832958,0.7390,0.0,1.0,0,False
10,2015-01-15,INFY,EQ,2128.65,2135.20,2152.80,2112.25,2130.00,2134.25,2137.46,2085613,4.457911e+14,48882,1410992,0.6765,0.0,0.0,0,False
11,2015-01-16,INFY,EQ,2134.25,2148.00,2160.00,2112.00,2115.00,2118.30,2125.77,1672740,3.555858e+14,63848,1254004,0.7497,0.0,0.0,0,False
12,2015-01-19,INFY,EQ,2118.30,2120.00,2132.35,2094.60,2105.00,2102.50,2104.55,1021936,2.150713e+14,62963,673948,0.6595,1.0,1.0,1,True
13,2015-01-20,INFY,EQ,2102.50,2107.00,2133.00,2101.45,2119.20,2124.20,2118.16,1701126,3.603258e+14,66871,1284137,0.7549,1.0,1.0,1,True
14,2015-01-21,INFY,EQ,2124.20,2131.50,2175.95,2118.00,2172.00,2169.90,2148.41,2123727,4.562628e+14,82679,1394125,0.6565,1.0,1.0,1,True
15,2015-01-22,INFY,EQ,2169.90,2174.80,2203.00,2161.30,2194.95,2196.45,2193.10,2489599,5.459951e+14,82961,1879561,0.7550,0.0,1.0,0,False
16,2015-01-23,INFY,EQ,2196.45,2200.00,2225.00,2165.10,2211.90,2215.05,2194.58,2371582,5.204624e+14,78929,1622130,0.6840,1.0,0.0,1,False
17,2015-01-27,INFY,EQ,2215.05,2221.00,2221.00,2130.10,2137.55,2136.50,2146.45,3434992,7.373022e+14,117167,2765575,0.8051,0.0,1.0,0,False
18,2015-01-28,INFY,EQ,2136.50,2150.00,2154.80,2130.30,2144.45,2144.55,2144.31,3283589,7.041041e+14,99134,2313485,0.7046,1.0,1.0,1,True
19,2015-01-29,INFY,EQ,2144.55,2145.00,2149.90,2127.60,2147.80,2145.50,2141.67,3842356,8.229076e+14,79209,2797911,0.7282,0.0,0.0,0,False
20,2015-01-30,INFY,EQ,2145.50,2161.50,2162.55,2126.95,2141.85,2141.90,2144.44,2708436,5.808066e+14,99180,2093132,0.7728,0.0,0.0,0,False
21,2015-02-02,INFY,EQ,2141.90,2141.50,2152.00,2126.05,2137.00,2136.85,2142.80,2175635,4.661958e+14,47871,1641719,0.7546,0.0,0.0,0,False
22,2015-02-03,INFY,EQ,2136.85,2136.85,2139.95,2102.00,2124.00,2120.90,2117.92,1316489,2.788217e+14,64490,821456,0.6240,0.0,1.0,0,False
23,2015-02-04,INFY,EQ,2120.90,2139.90,2150.00,2126.40,2143.80,2142.85,2142.92,1290004,2.764378e+14,49317,889211,0.6893,1.0,1.0,1,True
24,2015-02-05,INFY,EQ,2142.85,2150.80,2220.00,2148.00,2186.00,2193.80,2189.61,2968984,6.500912e+14,112707,2025011,0.6821,0.0,1.0,0,False
25,2015-02-06,INFY,EQ,2193.80,2205.00,2247.80,2188.50,2228.00,2230.50,2229.51,1863432,4.154534e+14,79072,1073921,0.5763,0.0,1.0,0,False
26,2015-02-09,INFY,EQ,2230.50,2200.00,2254.00,2200.00,2245.00,2248.90,2238.75,1634217,3.658597e+14,96994,1074815,0.6577,1.0,1.0,1,True
27,2015-02-10,INFY,EQ,2248.90,2243.00,2298.00,2241.00,2268.00,2278.30,2270.89,2129230,4.835242e+14,84805,1385146,0.6505,0.0,1.0,0,False
28,2015-02-11,INFY,EQ,2278.30,2280.50,2293.20,2256.25,2287.80,2284.85,2279.82,1449243,3.304009e+14,58510,962023,0.6638,0.0,1.0,0,False
29,2015-02-12,INFY,EQ,2284.85,2283.00,2321.95,2273.00,2309.90,2311.20,2301.63,1571884,3.617897e+14,66827,995751,0.6335,0.0,0.0,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2015-11-19,INFY,EQ,1020.00,1030.25,1052.00,1023.80,1048.00,1047.80,1038.56,4269811,4.434439e+14,169433,2638720,0.6180,0.0,1.0,0,False
220,2015-11-20,INFY,EQ,1047.80,1048.00,1063.20,1042.05,1051.00,1052.40,1053.83,3041489,3.205220e+14,151348,1851747,0.6088,0.0,1.0,0,False
221,2015-11-23,INFY,EQ,1052.40,1050.00,1062.40,1038.00,1052.00,1053.70,1053.76,2808175,2.959156e+14,90521,1799534,0.6408,0.0,0.0,0,False
222,2015-11-24,INFY,EQ,1053.70,1050.00,1050.80,1037.00,1040.70,1041.15,1043.40,2162901,2.256779e+14,58310,1249010,0.5775,1.0,1.0,1,True
223,2015-11-26,INFY,EQ,1041.15,1040.95,1059.50,1040.05,1050.00,1052.40,1051.79,4926984,5.182137e+14,114757,3656974,0.7422,0.0,1.0,0,False
224,2015-11-27,INFY,EQ,1052.40,1058.00,1070.00,1045.00,1066.00,1066.35,1060.99,2571239,2.728063e+14,69214,1799884,0.7000,1.0,1.0,1,True
225,2015-11-30,INFY,EQ,1066.35,1070.00,1098.30,1056.20,1083.05,1087.90,1083.44,9052767,9.808155e+14,108763,5565189,0.6148,0.0,0.0,0,False
226,2015-12-01,INFY,EQ,1087.90,1088.00,1095.00,1072.95,1075.45,1079.00,1082.42,2949275,3.192357e+14,76585,1982960,0.6724,0.0,0.0,0,False
227,2015-12-02,INFY,EQ,1079.00,1079.95,1079.95,1059.00,1061.10,1060.70,1064.12,3198808,3.403929e+14,90123,2139233,0.6688,0.0,0.0,0,False
228,2015-12-03,INFY,EQ,1060.70,1061.00,1064.80,1049.05,1059.00,1057.75,1056.77,2752363,2.908624e+14,110543,1838358,0.6679,1.0,0.0,1,False
229,2015-12-04,INFY,EQ,1057.75,1049.00,1064.90,1040.10,1048.85,1049.05,1047.32,4187765,4.385928e+14,209805,3031773,0.7240,0.0,0.0,0,False
230,2015-12-07,INFY,EQ,1049.05,1055.30,1059.00,1040.00,1046.00,1046.25,1048.08,2256935,2.365448e+14,65005,1441112,0.6385,1.0,0.0,1,False
231,2015-12-08,INFY,EQ,1046.25,1045.05,1062.75,1039.30,1042.00,1044.40,1051.88,2862186,3.010684e+14,87394,1790175,0.6255,1.0,0.0,1,False
232,2015-12-09,INFY,EQ,1044.40,1043.00,1046.95,1022.55,1024.00,1028.20,1036.19,3409127,3.532487e+14,85433,2068578,0.6068,0.0,1.0,0,False
233,2015-12-10,INFY,EQ,1028.20,1036.60,1051.60,1030.30,1049.90,1047.35,1040.47,2793873,2.906945e+14,80028,1838589,0.6581,0.0,1.0,0,False
234,2015-12-11,INFY,EQ,1047.35,1054.00,1061.90,1045.90,1055.65,1052.80,1052.88,2695099,2.837607e+14,84930,1623053,0.6022,0.0,1.0,0,False
235,2015-12-14,INFY,EQ,1052.80,1049.50,1073.15,1048.05,1067.50,1069.50,1066.30,2408336,2.568018e+14,104978,1419333,0.5893,1.0,1.0,1,True
236,2015-12-15,INFY,EQ,1069.50,1073.25,1079.10,1058.80,1078.50,1077.55,1071.44,2715904,2.909926e+14,76821,1951187,0.7184,0.0,1.0,0,False
237,2015-12-16,INFY,EQ,1077.55,1083.40,1098.00,1083.40,1094.00,1095.85,1092.86,2747926,3.003094e+14,66894,1988090,0.7235,0.0,1.0,0,False
238,2015-12-17,INFY,EQ,1095.85,1100.00,1109.80,1088.00,1105.50,1107.10,1099.83,2479391,2.726907e+14,87599,1294917,0.5223,1.0,0.0,1,False
239,2015-12-18,INFY,EQ,1107.10,1103.40,1103.40,1079.45,1085.95,1083.15,1086.91,3609910,3.923651e+14,65866,2604590,0.7215,0.0,1.0,0,False
240,2015-12-21,INFY,EQ,1083.15,1077.00,1107.40,1065.95,1107.00,1103.45,1095.68,2165506,2.372707e+14,61692,1223571,0.5650,0.0,0.0,0,False
241,2015-12-22,INFY,EQ,1103.45,1097.45,1097.45,1080.10,1085.00,1083.75,1085.81,2054627,2.230939e+14,51963,1204818,0.5864,0.0,1.0,0,False
242,2015-12-23,INFY,EQ,1083.75,1095.05,1102.50,1087.05,1100.00,1100.85,1097.35,1435464,1.575200e+14,38571,861318,0.6000,0.0,0.0,0,False
243,2015-12-24,INFY,EQ,1100.85,1102.05,1104.45,1090.10,1095.80,1096.35,1095.84,615027,6.739696e+13,20528,294731,0.4792,1.0,1.0,1,True
244,2015-12-28,INFY,EQ,1096.35,1090.00,1110.00,1090.00,1103.80,1104.75,1105.51,2763476,3.055046e+14,51103,1880078,0.6803,0.0,0.0,0,False
245,2015-12-29,INFY,EQ,1104.75,1101.25,1110.00,1097.30,1103.00,1104.70,1104.14,1672531,1.846706e+14,52409,967577,0.5785,1.0,0.0,1,False
246,2015-12-30,INFY,EQ,1104.70,1101.10,1106.60,1083.00,1088.00,1086.30,1094.45,2576985,2.820380e+14,65379,1754378,0.6808,1.0,1.0,1,True
247,2015-12-31,INFY,EQ,1086.30,1090.15,1109.95,1087.00,1107.00,1105.40,1102.09,3971969,4.377467e+14,75143,2641827,0.6651,0.0,0.0,0,False
248,2016-01-01,INFY,EQ,1105.40,1100.00,1108.95,1093.20,1103.00,1105.25,1103.13,903275,9.964333e+13,18982,331554,0.3671,NaN,NaN,1,False

In [51]:
import bokeh
from bokeh.plotting import figure, output_file, show
from bokeh.io import show, output_notebook
from bokeh.palettes import Blues9
from bokeh.palettes import RdBu3
from bokeh.models import ColumnDataSource, CategoricalColorMapper, ContinuousColorMapper
from bokeh.palettes import Spectral11

In [49]:
def bokeh_plot(stock):
    data = dict(stock=stock['Close'], Date=stock.index)
    
    p = figure(plot_width=800, plot_height=250)
    p.line(stock.index, stock['Close'], color='blue', alpha=0.5)
    
    #show price shock w/o vol shock
    
    p.circle(stock.index, stock.Close*stock["price_shock_w/0_vol_shock"], size=4, legend='price shock without vol shock')
    show(p)

In [50]:
bokeh_plot(infydf)