In [1]:
import pandas as pd
import numpy as np
from nsepy import get_history,get_index_pe_history
import datetime as dt

In [2]:
start = dt.datetime(2015,1,1)

end = dt.datetime(2016,1,1)

tcs = get_history(symbol='TCS', start = start, end = end)
tcs.index = pd.to_datetime(tcs.index)
tcs.head(10)

,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,,,
2015-01-01,TCS,EQ,2558.25,2567.0,2567.00,2541.00,2550.00,2545.55,2548.51,183415,4.674345e+13,8002,52870,0.2883
2015-01-02,TCS,EQ,2545.55,2551.0,2590.95,2550.60,2588.40,2579.45,2568.19,462870,1.188740e+14,27585,309350,0.6683
2015-01-05,TCS,EQ,2579.45,2581.0,2599.90,2524.65,2538.10,2540.25,2563.94,877121,2.248886e+14,43234,456728,0.5207
2015-01-06,TCS,EQ,2540.25,2529.1,2529.10,2440.00,2450.05,2446.60,2466.90,1211892,2.989615e+14,84503,714306,0.5894
2015-01-07,TCS,EQ,2446.60,2470.0,2479.15,2407.45,2426.90,2417.70,2433.96,1318166,3.208362e+14,101741,886368,0.6724
2015-01-08,TCS,EQ,2417.70,2442.4,2449.00,2420.55,2446.00,2443.80,2434.81,782704,1.905739e+14,47699,450768,0.5759
2015-01-09,TCS,EQ,2443.80,2455.0,2519.90,2450.00,2510.00,2512.30,2490.01,1598821,3.981082e+14,81743,865777,0.5415
2015-01-12,TCS,EQ,2512.30,2517.0,2528.00,2480.25,2527.95,2509.70,2497.82,798003,1.993266e+14,58810,451228,0.5654
2015-01-13,TCS,EQ,2509.70,2520.0,2530.40,2480.10,2498.00,2497.90,2509.40,734216,1.842440e+14,49993,386133,0.5259
2015-01-14,TCS,EQ,2497.90,2516.0,2531.80,2500.50,2525.05,2521.95,2517.54,893548,2.249546e+14,69237,498193,0.5575

In [5]:
new_tcs=tcs.reset_index()
new_tcs['Date']=pd.to_datetime(new_tcs['Date'])
new_tcs.head()

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2015-01-01,TCS,EQ,2558.25,2567.0,2567.00,2541.00,2550.00,2545.55,2548.51,183415,4.674345e+13,8002,52870,0.2883
1,2015-01-02,TCS,EQ,2545.55,2551.0,2590.95,2550.60,2588.40,2579.45,2568.19,462870,1.188740e+14,27585,309350,0.6683
2,2015-01-05,TCS,EQ,2579.45,2581.0,2599.90,2524.65,2538.10,2540.25,2563.94,877121,2.248886e+14,43234,456728,0.5207
3,2015-01-06,TCS,EQ,2540.25,2529.1,2529.10,2440.00,2450.05,2446.60,2466.90,1211892,2.989615e+14,84503,714306,0.5894
4,2015-01-07,TCS,EQ,2446.60,2470.0,2479.15,2407.45,2426.90,2417.70,2433.96,1318166,3.208362e+14,101741,886368,0.6724

In [6]:
#moving average
def SMA(data, ndays): 
 SMA = pd.Series((data['Close']).rolling(window=ndays).mean(),name = 'SMA')
 data = data.join(SMA) 
 return data

In [7]:
#moving average for 4 weeks - if there are 5 working days, then n = 20
SMA(new_tcs, 20)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,SMA
0,2015-01-01,TCS,EQ,2558.25,2567.00,2567.00,2541.00,2550.00,2545.55,2548.51,183415,4.674345e+13,8002,52870,0.2883,NaN
1,2015-01-02,TCS,EQ,2545.55,2551.00,2590.95,2550.60,2588.40,2579.45,2568.19,462870,1.188740e+14,27585,309350,0.6683,NaN
2,2015-01-05,TCS,EQ,2579.45,2581.00,2599.90,2524.65,2538.10,2540.25,2563.94,877121,2.248886e+14,43234,456728,0.5207,NaN
3,2015-01-06,TCS,EQ,2540.25,2529.10,2529.10,2440.00,2450.05,2446.60,2466.90,1211892,2.989615e+14,84503,714306,0.5894,NaN
4,2015-01-07,TCS,EQ,2446.60,2470.00,2479.15,2407.45,2426.90,2417.70,2433.96,1318166,3.208362e+14,101741,886368,0.6724,NaN
5,2015-01-08,TCS,EQ,2417.70,2442.40,2449.00,2420.55,2446.00,2443.80,2434.81,782704,1.905739e+14,47699,450768,0.5759,NaN
6,2015-01-09,TCS,EQ,2443.80,2455.00,2519.90,2450.00,2510.00,2512.30,2490.01,1598821,3.981082e+14,81743,865777,0.5415,NaN
7,2015-01-12,TCS,EQ,2512.30,2517.00,2528.00,2480.25,2527.95,2509.70,2497.82,798003,1.993266e+14,58810,451228,0.5654,NaN
8,2015-01-13,TCS,EQ,2509.70,2520.00,2530.40,2480.10,2498.00,2497.90,2509.40,734216,1.842440e+14,49993,386133,0.5259,NaN
9,2015-01-14,TCS,EQ,2497.90,2516.00,2531.80,2500.50,2525.05,2521.95,2517.54,893548,2.249546e+14,69237,498193,0.5575,NaN
10,2015-01-15,TCS,EQ,2521.95,2533.00,2581.75,2523.25,2542.05,2539.10,2550.97,2504960,6.390076e+14,96363,1598846,0.6383,NaN
11,2015-01-16,TCS,EQ,2539.10,2543.70,2545.00,2484.30,2526.00,2532.15,2511.39,2646915,6.647444e+14,127847,1372200,0.5184,NaN
12,2015-01-19,TCS,EQ,2532.15,2536.00,2551.00,2503.00,2509.00,2511.00,2516.06,567537,1.427954e+14,38860,309156,0.5447,NaN
13,2015-01-20,TCS,EQ,2511.00,2520.00,2530.00,2483.25,2498.00,2500.45,2498.94,1029283,2.572121e+14,58066,733487,0.7126,NaN
14,2015-01-21,TCS,EQ,2500.45,2522.00,2522.00,2488.25,2518.00,2513.80,2507.75,1155240,2.897055e+14,75976,771316,0.6677,NaN
15,2015-01-22,TCS,EQ,2513.80,2516.50,2521.25,2495.50,2511.00,2513.55,2509.31,1056607,2.651355e+14,74837,742399,0.7026,NaN
16,2015-01-23,TCS,EQ,2513.55,2514.00,2532.05,2496.10,2504.10,2503.60,2507.34,1575190,3.949530e+14,94619,1205911,0.7656,NaN
17,2015-01-27,TCS,EQ,2503.60,2512.35,2515.00,2489.55,2504.20,2502.05,2502.26,1369368,3.426510e+14,71406,1079233,0.7881,NaN
18,2015-01-28,TCS,EQ,2502.05,2503.00,2544.90,2502.90,2533.40,2539.60,2529.32,1560990,3.948240e+14,101994,1142166,0.7317,NaN
19,2015-01-29,TCS,EQ,2539.60,2538.00,2568.70,2512.90,2560.70,2544.65,2531.88,1867196,4.727520e+14,67497,1547590,0.8288,2510.7575
20,2015-01-30,TCS,EQ,2544.65,2560.70,2575.00,2470.00,2484.00,2482.05,2494.94,2908701,7.257025e+14,119200,2355497,0.8098,2507.5825
21,2015-02-02,TCS,EQ,2482.05,2482.00,2521.45,2462.05,2516.00,2514.20,2500.60,1590901,3.978211e+14,89485,1171718,0.7365,2504.3200
22,2015-02-03,TCS,EQ,2514.20,2511.65,2565.00,2507.10,2552.25,2558.25,2536.23,1172527,2.973793e+14,75106,701449,0.5982,2505.2200
23,2015-02-04,TCS,EQ,2558.25,2568.00,2571.70,2502.10,2514.95,2514.30,2523.08,1122709,2.832687e+14,60615,807091,0.7189,2508.6050
24,2015-02-05,TCS,EQ,2514.30,2520.00,2591.70,2519.00,2553.00,2552.40,2558.13,2265084,5.794386e+14,77935,1638106,0.7232,2515.3400
25,2015-02-06,TCS,EQ,2552.40,2553.00,2594.80,2550.85,2576.10,2575.75,2578.40,1068208,2.754265e+14,82449,582019,0.5449,2521.9375
26,2015-02-09,TCS,EQ,2575.75,2561.50,2569.10,2500.00,2512.00,2512.90,2531.83,1038216,2.628585e+14,72967,695542,0.6699,2521.9675
27,2015-02-10,TCS,EQ,2512.90,2510.00,2526.25,2433.00,2445.50,2441.15,2473.88,1899527,4.699201e+14,114773,1383973,0.7286,2518.5400
28,2015-02-11,TCS,EQ,2441.15,2455.05,2487.25,2447.25,2460.00,2459.90,2468.94,1468761,3.626283e+14,115345,1143243,0.7784,2516.6400
29,2015-02-12,TCS,EQ,2459.90,2479.80,2479.80,2447.00,2469.00,2462.15,2462.56,1553990,3.826787e+14,113845,1269759,0.8171,2513.6500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2015-11-19,TCS,EQ,2351.45,2365.35,2381.60,2352.00,2367.00,2362.55,2366.14,933453,2.208681e+14,55764,632570,0.6777,2475.6150
220,2015-11-20,TCS,EQ,2362.55,2366.50,2423.55,2361.95,2394.50,2398.35,2403.22,1006063,2.417790e+14,60130,575994,0.5725,2469.0325
221,2015-11-23,TCS,EQ,2398.35,2405.30,2413.40,2382.25,2389.30,2391.05,2397.62,544041,1.304405e+14,42359,351815,0.6467,2461.7275
222,2015-11-24,TCS,EQ,2391.05,2380.05,2392.45,2365.50,2366.00,2367.95,2378.62,499320,1.187695e+14,35776,342427,0.6858,2453.2975
223,2015-11-26,TCS,EQ,2367.95,2377.90,2382.40,2337.85,2346.00,2345.55,2355.52,1457646,3.433509e+14,77452,969589,0.6652,2444.0200
224,2015-11-27,TCS,EQ,2345.55,2348.00,2359.45,2332.50,2354.95,2353.35,2348.70,868603,2.040086e+14,62719,518858,0.5973,2435.2325
225,2015-11-30,TCS,EQ,2353.35,2365.00,2391.25,2350.15,2373.55,2364.70,2365.21,2050024,4.848745e+14,85439,1102521,0.5378,2428.7000
226,2015-12-01,TCS,EQ,2364.70,2362.90,2378.05,2357.05,2359.75,2361.90,2363.85,860997,2.035267e+14,51511,672976,0.7816,2422.0350
227,2015-12-02,TCS,EQ,2361.90,2378.00,2378.10,2346.50,2367.00,2365.20,2362.86,820148,1.937896e+14,38694,580713,0.7081,2414.4275
228,2015-12-03,TCS,EQ,2365.20,2360.00,2373.00,2347.00,2350.00,2350.75,2356.59,1141679,2.690468e+14,41715,765969,0.6709,2404.7925
229,2015-12-04,TCS,EQ,2350.75,2340.00,2347.30,2321.10,2330.00,2328.40,2330.08,623046,1.451747e+14,32999,426970,0.6853,2394.5225
230,2015-12-07,TCS,EQ,2328.40,2332.20,2343.90,2315.25,2321.00,2319.80,2322.27,691302,1.605390e+14,52150,487587,0.7053,2386.3800
231,2015-12-08,TCS,EQ,2319.80,2319.40,2349.00,2317.30,2326.25,2329.00,2332.95,569982,1.329739e+14,47957,336913,0.5911,2377.5425
232,2015-12-09,TCS,EQ,2329.00,2337.90,2372.80,2320.00,2370.00,2367.65,2361.23,2641403,6.236954e+14,59592,1365071,0.5168,2372.3575
233,2015-12-10,TCS,EQ,2367.65,2369.00,2391.20,2352.00,2380.95,2384.55,2374.82,861994,2.047084e+14,52429,556996,0.6462,2368.6775
234,2015-12-11,TCS,EQ,2384.55,2383.00,2391.95,2363.25,2383.15,2386.00,2384.13,826189,1.969746e+14,53651,598804,0.7248,2364.5375
235,2015-12-14,TCS,EQ,2386.00,2335.20,2387.00,2330.60,2375.00,2378.45,2364.84,1359266,3.214443e+14,58637,758806,0.5582,2363.5900
236,2015-12-15,TCS,EQ,2378.45,2378.45,2385.00,2363.05,2379.50,2375.85,2375.03,567934,1.348859e+14,52585,421587,0.7423,2363.6525
237,2015-12-16,TCS,EQ,2375.85,2384.00,2414.50,2384.00,2407.50,2408.40,2402.07,717967,1.724609e+14,48074,494205,0.6883,2364.5450
238,2015-12-17,TCS,EQ,2408.40,2415.00,2445.00,2393.35,2434.10,2439.75,2418.57,809422,1.957647e+14,46818,569320,0.7034,2368.9600
239,2015-12-18,TCS,EQ,2439.75,2420.00,2434.20,2400.65,2409.80,2416.80,2416.02,1512485,3.654198e+14,47644,1052042,0.6956,2371.6725
240,2015-12-21,TCS,EQ,2416.80,2419.95,2450.00,2406.85,2443.00,2446.40,2428.40,805052,1.954989e+14,41004,425890,0.5290,2374.0750
241,2015-12-22,TCS,EQ,2446.40,2440.00,2440.00,2400.00,2407.00,2405.05,2413.33,780429,1.883430e+14,30995,476137,0.6101,2374.7750
242,2015-12-23,TCS,EQ,2405.05,2415.00,2435.00,2410.55,2418.80,2425.80,2425.06,424917,1.030449e+14,31057,253475,0.5965,2377.6675
243,2015-12-24,TCS,EQ,2425.80,2421.00,2438.20,2404.00,2435.00,2434.25,2424.03,421580,1.021924e+14,21932,188670,0.4475,2382.1025
244,2015-12-28,TCS,EQ,2434.25,2428.00,2466.40,2420.20,2456.95,2462.70,2455.00,1852099,4.546896e+14,43390,1060100,0.5724,2387.5700
245,2015-12-29,TCS,EQ,2462.70,2458.35,2465.30,2445.75,2449.35,2455.80,2452.26,854262,2.094875e+14,26975,433986,0.5080,2392.1250
246,2015-12-30,TCS,EQ,2455.80,2453.05,2459.00,2412.30,2421.70,2418.30,2442.06,802881,1.960682e+14,49464,632180,0.7874,2394.9450
247,2015-12-31,TCS,EQ,2418.30,2415.75,2448.50,2407.50,2430.00,2436.85,2428.90,620159,1.506303e+14,42600,400391,0.6456,2398.5275
248,2016-01-01,TCS,EQ,2436.85,2439.00,2439.00,2412.25,2414.10,2416.40,2423.73,356131,8.631649e+13,15545,246115,0.6911,2401.8100

In [8]:
#moving average for 16 weeks - if there are 5 working days, then n = 80
SMA(new_tcs, 80)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,SMA
0,2015-01-01,TCS,EQ,2558.25,2567.00,2567.00,2541.00,2550.00,2545.55,2548.51,183415,4.674345e+13,8002,52870,0.2883,NaN
1,2015-01-02,TCS,EQ,2545.55,2551.00,2590.95,2550.60,2588.40,2579.45,2568.19,462870,1.188740e+14,27585,309350,0.6683,NaN
2,2015-01-05,TCS,EQ,2579.45,2581.00,2599.90,2524.65,2538.10,2540.25,2563.94,877121,2.248886e+14,43234,456728,0.5207,NaN
3,2015-01-06,TCS,EQ,2540.25,2529.10,2529.10,2440.00,2450.05,2446.60,2466.90,1211892,2.989615e+14,84503,714306,0.5894,NaN
4,2015-01-07,TCS,EQ,2446.60,2470.00,2479.15,2407.45,2426.90,2417.70,2433.96,1318166,3.208362e+14,101741,886368,0.6724,NaN
5,2015-01-08,TCS,EQ,2417.70,2442.40,2449.00,2420.55,2446.00,2443.80,2434.81,782704,1.905739e+14,47699,450768,0.5759,NaN
6,2015-01-09,TCS,EQ,2443.80,2455.00,2519.90,2450.00,2510.00,2512.30,2490.01,1598821,3.981082e+14,81743,865777,0.5415,NaN
7,2015-01-12,TCS,EQ,2512.30,2517.00,2528.00,2480.25,2527.95,2509.70,2497.82,798003,1.993266e+14,58810,451228,0.5654,NaN
8,2015-01-13,TCS,EQ,2509.70,2520.00,2530.40,2480.10,2498.00,2497.90,2509.40,734216,1.842440e+14,49993,386133,0.5259,NaN
9,2015-01-14,TCS,EQ,2497.90,2516.00,2531.80,2500.50,2525.05,2521.95,2517.54,893548,2.249546e+14,69237,498193,0.5575,NaN
10,2015-01-15,TCS,EQ,2521.95,2533.00,2581.75,2523.25,2542.05,2539.10,2550.97,2504960,6.390076e+14,96363,1598846,0.6383,NaN
11,2015-01-16,TCS,EQ,2539.10,2543.70,2545.00,2484.30,2526.00,2532.15,2511.39,2646915,6.647444e+14,127847,1372200,0.5184,NaN
12,2015-01-19,TCS,EQ,2532.15,2536.00,2551.00,2503.00,2509.00,2511.00,2516.06,567537,1.427954e+14,38860,309156,0.5447,NaN
13,2015-01-20,TCS,EQ,2511.00,2520.00,2530.00,2483.25,2498.00,2500.45,2498.94,1029283,2.572121e+14,58066,733487,0.7126,NaN
14,2015-01-21,TCS,EQ,2500.45,2522.00,2522.00,2488.25,2518.00,2513.80,2507.75,1155240,2.897055e+14,75976,771316,0.6677,NaN
15,2015-01-22,TCS,EQ,2513.80,2516.50,2521.25,2495.50,2511.00,2513.55,2509.31,1056607,2.651355e+14,74837,742399,0.7026,NaN
16,2015-01-23,TCS,EQ,2513.55,2514.00,2532.05,2496.10,2504.10,2503.60,2507.34,1575190,3.949530e+14,94619,1205911,0.7656,NaN
17,2015-01-27,TCS,EQ,2503.60,2512.35,2515.00,2489.55,2504.20,2502.05,2502.26,1369368,3.426510e+14,71406,1079233,0.7881,NaN
18,2015-01-28,TCS,EQ,2502.05,2503.00,2544.90,2502.90,2533.40,2539.60,2529.32,1560990,3.948240e+14,101994,1142166,0.7317,NaN
19,2015-01-29,TCS,EQ,2539.60,2538.00,2568.70,2512.90,2560.70,2544.65,2531.88,1867196,4.727520e+14,67497,1547590,0.8288,NaN
20,2015-01-30,TCS,EQ,2544.65,2560.70,2575.00,2470.00,2484.00,2482.05,2494.94,2908701,7.257025e+14,119200,2355497,0.8098,NaN
21,2015-02-02,TCS,EQ,2482.05,2482.00,2521.45,2462.05,2516.00,2514.20,2500.60,1590901,3.978211e+14,89485,1171718,0.7365,NaN
22,2015-02-03,TCS,EQ,2514.20,2511.65,2565.00,2507.10,2552.25,2558.25,2536.23,1172527,2.973793e+14,75106,701449,0.5982,NaN
23,2015-02-04,TCS,EQ,2558.25,2568.00,2571.70,2502.10,2514.95,2514.30,2523.08,1122709,2.832687e+14,60615,807091,0.7189,NaN
24,2015-02-05,TCS,EQ,2514.30,2520.00,2591.70,2519.00,2553.00,2552.40,2558.13,2265084,5.794386e+14,77935,1638106,0.7232,NaN
25,2015-02-06,TCS,EQ,2552.40,2553.00,2594.80,2550.85,2576.10,2575.75,2578.40,1068208,2.754265e+14,82449,582019,0.5449,NaN
26,2015-02-09,TCS,EQ,2575.75,2561.50,2569.10,2500.00,2512.00,2512.90,2531.83,1038216,2.628585e+14,72967,695542,0.6699,NaN
27,2015-02-10,TCS,EQ,2512.90,2510.00,2526.25,2433.00,2445.50,2441.15,2473.88,1899527,4.699201e+14,114773,1383973,0.7286,NaN
28,2015-02-11,TCS,EQ,2441.15,2455.05,2487.25,2447.25,2460.00,2459.90,2468.94,1468761,3.626283e+14,115345,1143243,0.7784,NaN
29,2015-02-12,TCS,EQ,2459.90,2479.80,2479.80,2447.00,2469.00,2462.15,2462.56,1553990,3.826787e+14,113845,1269759,0.8171,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2015-11-19,TCS,EQ,2351.45,2365.35,2381.60,2352.00,2367.00,2362.55,2366.14,933453,2.208681e+14,55764,632570,0.6777,2551.544375
220,2015-11-20,TCS,EQ,2362.55,2366.50,2423.55,2361.95,2394.50,2398.35,2403.22,1006063,2.417790e+14,60130,575994,0.5725,2550.209375
221,2015-11-23,TCS,EQ,2398.35,2405.30,2413.40,2382.25,2389.30,2391.05,2397.62,544041,1.304405e+14,42359,351815,0.6467,2548.884375
222,2015-11-24,TCS,EQ,2391.05,2380.05,2392.45,2365.50,2366.00,2367.95,2378.62,499320,1.187695e+14,35776,342427,0.6858,2547.208125
223,2015-11-26,TCS,EQ,2367.95,2377.90,2382.40,2337.85,2346.00,2345.55,2355.52,1457646,3.433509e+14,77452,969589,0.6652,2545.193125
224,2015-11-27,TCS,EQ,2345.55,2348.00,2359.45,2332.50,2354.95,2353.35,2348.70,868603,2.040086e+14,62719,518858,0.5973,2543.601875
225,2015-11-30,TCS,EQ,2353.35,2365.00,2391.25,2350.15,2373.55,2364.70,2365.21,2050024,4.848745e+14,85439,1102521,0.5378,2541.776250
226,2015-12-01,TCS,EQ,2364.70,2362.90,2378.05,2357.05,2359.75,2361.90,2363.85,860997,2.035267e+14,51511,672976,0.7816,2539.930000
227,2015-12-02,TCS,EQ,2361.90,2378.00,2378.10,2346.50,2367.00,2365.20,2362.86,820148,1.937896e+14,38694,580713,0.7081,2538.133750
228,2015-12-03,TCS,EQ,2365.20,2360.00,2373.00,2347.00,2350.00,2350.75,2356.59,1141679,2.690468e+14,41715,765969,0.6709,2535.678750
229,2015-12-04,TCS,EQ,2350.75,2340.00,2347.30,2321.10,2330.00,2328.40,2330.08,623046,1.451747e+14,32999,426970,0.6853,2532.617500
230,2015-12-07,TCS,EQ,2328.40,2332.20,2343.90,2315.25,2321.00,2319.80,2322.27,691302,1.605390e+14,52150,487587,0.7053,2529.714375
231,2015-12-08,TCS,EQ,2319.80,2319.40,2349.00,2317.30,2326.25,2329.00,2332.95,569982,1.329739e+14,47957,336913,0.5911,2526.675625
232,2015-12-09,TCS,EQ,2329.00,2337.90,2372.80,2320.00,2370.00,2367.65,2361.23,2641403,6.236954e+14,59592,1365071,0.5168,2523.718750
233,2015-12-10,TCS,EQ,2367.65,2369.00,2391.20,2352.00,2380.95,2384.55,2374.82,861994,2.047084e+14,52429,556996,0.6462,2520.129375
234,2015-12-11,TCS,EQ,2384.55,2383.00,2391.95,2363.25,2383.15,2386.00,2384.13,826189,1.969746e+14,53651,598804,0.7248,2517.009375
235,2015-12-14,TCS,EQ,2386.00,2335.20,2387.00,2330.60,2375.00,2378.45,2364.84,1359266,3.214443e+14,58637,758806,0.5582,2512.950000
236,2015-12-15,TCS,EQ,2378.45,2378.45,2385.00,2363.05,2379.50,2375.85,2375.03,567934,1.348859e+14,52585,421587,0.7423,2509.088750
237,2015-12-16,TCS,EQ,2375.85,2384.00,2414.50,2384.00,2407.50,2408.40,2402.07,717967,1.724609e+14,48074,494205,0.6883,2504.932500
238,2015-12-17,TCS,EQ,2408.40,2415.00,2445.00,2393.35,2434.10,2439.75,2418.57,809422,1.957647e+14,46818,569320,0.7034,2501.259375
239,2015-12-18,TCS,EQ,2439.75,2420.00,2434.20,2400.65,2409.80,2416.80,2416.02,1512485,3.654198e+14,47644,1052042,0.6956,2497.883750
240,2015-12-21,TCS,EQ,2416.80,2419.95,2450.00,2406.85,2443.00,2446.40,2428.40,805052,1.954989e+14,41004,425890,0.5290,2495.011875
241,2015-12-22,TCS,EQ,2446.40,2440.00,2440.00,2400.00,2407.00,2405.05,2413.33,780429,1.883430e+14,30995,476137,0.6101,2492.841875
242,2015-12-23,TCS,EQ,2405.05,2415.00,2435.00,2410.55,2418.80,2425.80,2425.06,424917,1.030449e+14,31057,253475,0.5965,2491.075000
243,2015-12-24,TCS,EQ,2425.80,2421.00,2438.20,2404.00,2435.00,2434.25,2424.03,421580,1.021924e+14,21932,188670,0.4475,2489.293750
244,2015-12-28,TCS,EQ,2434.25,2428.00,2466.40,2420.20,2456.95,2462.70,2455.00,1852099,4.546896e+14,43390,1060100,0.5724,2487.894375
245,2015-12-29,TCS,EQ,2462.70,2458.35,2465.30,2445.75,2449.35,2455.80,2452.26,854262,2.094875e+14,26975,433986,0.5080,2486.456250
246,2015-12-30,TCS,EQ,2455.80,2453.05,2459.00,2412.30,2421.70,2418.30,2442.06,802881,1.960682e+14,49464,632180,0.7874,2484.634375
247,2015-12-31,TCS,EQ,2418.30,2415.75,2448.50,2407.50,2430.00,2436.85,2428.90,620159,1.506303e+14,42600,400391,0.6456,2483.377500
248,2016-01-01,TCS,EQ,2436.85,2439.00,2439.00,2412.25,2414.10,2416.40,2423.73,356131,8.631649e+13,15545,246115,0.6911,2481.185000

In [9]:
#moving average for 52 weeks - if there are 5 working days, then n = 260 but here i ll take n=240 due to data size
SMA(new_tcs, 240)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,SMA
0,2015-01-01,TCS,EQ,2558.25,2567.00,2567.00,2541.00,2550.00,2545.55,2548.51,183415,4.674345e+13,8002,52870,0.2883,NaN
1,2015-01-02,TCS,EQ,2545.55,2551.00,2590.95,2550.60,2588.40,2579.45,2568.19,462870,1.188740e+14,27585,309350,0.6683,NaN
2,2015-01-05,TCS,EQ,2579.45,2581.00,2599.90,2524.65,2538.10,2540.25,2563.94,877121,2.248886e+14,43234,456728,0.5207,NaN
3,2015-01-06,TCS,EQ,2540.25,2529.10,2529.10,2440.00,2450.05,2446.60,2466.90,1211892,2.989615e+14,84503,714306,0.5894,NaN
4,2015-01-07,TCS,EQ,2446.60,2470.00,2479.15,2407.45,2426.90,2417.70,2433.96,1318166,3.208362e+14,101741,886368,0.6724,NaN
5,2015-01-08,TCS,EQ,2417.70,2442.40,2449.00,2420.55,2446.00,2443.80,2434.81,782704,1.905739e+14,47699,450768,0.5759,NaN
6,2015-01-09,TCS,EQ,2443.80,2455.00,2519.90,2450.00,2510.00,2512.30,2490.01,1598821,3.981082e+14,81743,865777,0.5415,NaN
7,2015-01-12,TCS,EQ,2512.30,2517.00,2528.00,2480.25,2527.95,2509.70,2497.82,798003,1.993266e+14,58810,451228,0.5654,NaN
8,2015-01-13,TCS,EQ,2509.70,2520.00,2530.40,2480.10,2498.00,2497.90,2509.40,734216,1.842440e+14,49993,386133,0.5259,NaN
9,2015-01-14,TCS,EQ,2497.90,2516.00,2531.80,2500.50,2525.05,2521.95,2517.54,893548,2.249546e+14,69237,498193,0.5575,NaN
10,2015-01-15,TCS,EQ,2521.95,2533.00,2581.75,2523.25,2542.05,2539.10,2550.97,2504960,6.390076e+14,96363,1598846,0.6383,NaN
11,2015-01-16,TCS,EQ,2539.10,2543.70,2545.00,2484.30,2526.00,2532.15,2511.39,2646915,6.647444e+14,127847,1372200,0.5184,NaN
12,2015-01-19,TCS,EQ,2532.15,2536.00,2551.00,2503.00,2509.00,2511.00,2516.06,567537,1.427954e+14,38860,309156,0.5447,NaN
13,2015-01-20,TCS,EQ,2511.00,2520.00,2530.00,2483.25,2498.00,2500.45,2498.94,1029283,2.572121e+14,58066,733487,0.7126,NaN
14,2015-01-21,TCS,EQ,2500.45,2522.00,2522.00,2488.25,2518.00,2513.80,2507.75,1155240,2.897055e+14,75976,771316,0.6677,NaN
15,2015-01-22,TCS,EQ,2513.80,2516.50,2521.25,2495.50,2511.00,2513.55,2509.31,1056607,2.651355e+14,74837,742399,0.7026,NaN
16,2015-01-23,TCS,EQ,2513.55,2514.00,2532.05,2496.10,2504.10,2503.60,2507.34,1575190,3.949530e+14,94619,1205911,0.7656,NaN
17,2015-01-27,TCS,EQ,2503.60,2512.35,2515.00,2489.55,2504.20,2502.05,2502.26,1369368,3.426510e+14,71406,1079233,0.7881,NaN
18,2015-01-28,TCS,EQ,2502.05,2503.00,2544.90,2502.90,2533.40,2539.60,2529.32,1560990,3.948240e+14,101994,1142166,0.7317,NaN
19,2015-01-29,TCS,EQ,2539.60,2538.00,2568.70,2512.90,2560.70,2544.65,2531.88,1867196,4.727520e+14,67497,1547590,0.8288,NaN
20,2015-01-30,TCS,EQ,2544.65,2560.70,2575.00,2470.00,2484.00,2482.05,2494.94,2908701,7.257025e+14,119200,2355497,0.8098,NaN
21,2015-02-02,TCS,EQ,2482.05,2482.00,2521.45,2462.05,2516.00,2514.20,2500.60,1590901,3.978211e+14,89485,1171718,0.7365,NaN
22,2015-02-03,TCS,EQ,2514.20,2511.65,2565.00,2507.10,2552.25,2558.25,2536.23,1172527,2.973793e+14,75106,701449,0.5982,NaN
23,2015-02-04,TCS,EQ,2558.25,2568.00,2571.70,2502.10,2514.95,2514.30,2523.08,1122709,2.832687e+14,60615,807091,0.7189,NaN
24,2015-02-05,TCS,EQ,2514.30,2520.00,2591.70,2519.00,2553.00,2552.40,2558.13,2265084,5.794386e+14,77935,1638106,0.7232,NaN
25,2015-02-06,TCS,EQ,2552.40,2553.00,2594.80,2550.85,2576.10,2575.75,2578.40,1068208,2.754265e+14,82449,582019,0.5449,NaN
26,2015-02-09,TCS,EQ,2575.75,2561.50,2569.10,2500.00,2512.00,2512.90,2531.83,1038216,2.628585e+14,72967,695542,0.6699,NaN
27,2015-02-10,TCS,EQ,2512.90,2510.00,2526.25,2433.00,2445.50,2441.15,2473.88,1899527,4.699201e+14,114773,1383973,0.7286,NaN
28,2015-02-11,TCS,EQ,2441.15,2455.05,2487.25,2447.25,2460.00,2459.90,2468.94,1468761,3.626283e+14,115345,1143243,0.7784,NaN
29,2015-02-12,TCS,EQ,2459.90,2479.80,2479.80,2447.00,2469.00,2462.15,2462.56,1553990,3.826787e+14,113845,1269759,0.8171,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2015-11-19,TCS,EQ,2351.45,2365.35,2381.60,2352.00,2367.00,2362.55,2366.14,933453,2.208681e+14,55764,632570,0.6777,NaN
220,2015-11-20,TCS,EQ,2362.55,2366.50,2423.55,2361.95,2394.50,2398.35,2403.22,1006063,2.417790e+14,60130,575994,0.5725,NaN
221,2015-11-23,TCS,EQ,2398.35,2405.30,2413.40,2382.25,2389.30,2391.05,2397.62,544041,1.304405e+14,42359,351815,0.6467,NaN
222,2015-11-24,TCS,EQ,2391.05,2380.05,2392.45,2365.50,2366.00,2367.95,2378.62,499320,1.187695e+14,35776,342427,0.6858,NaN
223,2015-11-26,TCS,EQ,2367.95,2377.90,2382.40,2337.85,2346.00,2345.55,2355.52,1457646,3.433509e+14,77452,969589,0.6652,NaN
224,2015-11-27,TCS,EQ,2345.55,2348.00,2359.45,2332.50,2354.95,2353.35,2348.70,868603,2.040086e+14,62719,518858,0.5973,NaN
225,2015-11-30,TCS,EQ,2353.35,2365.00,2391.25,2350.15,2373.55,2364.70,2365.21,2050024,4.848745e+14,85439,1102521,0.5378,NaN
226,2015-12-01,TCS,EQ,2364.70,2362.90,2378.05,2357.05,2359.75,2361.90,2363.85,860997,2.035267e+14,51511,672976,0.7816,NaN
227,2015-12-02,TCS,EQ,2361.90,2378.00,2378.10,2346.50,2367.00,2365.20,2362.86,820148,1.937896e+14,38694,580713,0.7081,NaN
228,2015-12-03,TCS,EQ,2365.20,2360.00,2373.00,2347.00,2350.00,2350.75,2356.59,1141679,2.690468e+14,41715,765969,0.6709,NaN
229,2015-12-04,TCS,EQ,2350.75,2340.00,2347.30,2321.10,2330.00,2328.40,2330.08,623046,1.451747e+14,32999,426970,0.6853,NaN
230,2015-12-07,TCS,EQ,2328.40,2332.20,2343.90,2315.25,2321.00,2319.80,2322.27,691302,1.605390e+14,52150,487587,0.7053,NaN
231,2015-12-08,TCS,EQ,2319.80,2319.40,2349.00,2317.30,2326.25,2329.00,2332.95,569982,1.329739e+14,47957,336913,0.5911,NaN
232,2015-12-09,TCS,EQ,2329.00,2337.90,2372.80,2320.00,2370.00,2367.65,2361.23,2641403,6.236954e+14,59592,1365071,0.5168,NaN
233,2015-12-10,TCS,EQ,2367.65,2369.00,2391.20,2352.00,2380.95,2384.55,2374.82,861994,2.047084e+14,52429,556996,0.6462,NaN
234,2015-12-11,TCS,EQ,2384.55,2383.00,2391.95,2363.25,2383.15,2386.00,2384.13,826189,1.969746e+14,53651,598804,0.7248,NaN
235,2015-12-14,TCS,EQ,2386.00,2335.20,2387.00,2330.60,2375.00,2378.45,2364.84,1359266,3.214443e+14,58637,758806,0.5582,NaN
236,2015-12-15,TCS,EQ,2378.45,2378.45,2385.00,2363.05,2379.50,2375.85,2375.03,567934,1.348859e+14,52585,421587,0.7423,NaN
237,2015-12-16,TCS,EQ,2375.85,2384.00,2414.50,2384.00,2407.50,2408.40,2402.07,717967,1.724609e+14,48074,494205,0.6883,NaN
238,2015-12-17,TCS,EQ,2408.40,2415.00,2445.00,2393.35,2434.10,2439.75,2418.57,809422,1.957647e+14,46818,569320,0.7034,NaN
239,2015-12-18,TCS,EQ,2439.75,2420.00,2434.20,2400.65,2409.80,2416.80,2416.02,1512485,3.654198e+14,47644,1052042,0.6956,2541.120417
240,2015-12-21,TCS,EQ,2416.80,2419.95,2450.00,2406.85,2443.00,2446.40,2428.40,805052,1.954989e+14,41004,425890,0.5290,2540.707292
241,2015-12-22,TCS,EQ,2446.40,2440.00,2440.00,2400.00,2407.00,2405.05,2413.33,780429,1.883430e+14,30995,476137,0.6101,2539.980625
242,2015-12-23,TCS,EQ,2405.05,2415.00,2435.00,2410.55,2418.80,2425.80,2425.06,424917,1.030449e+14,31057,253475,0.5965,2539.503750
243,2015-12-24,TCS,EQ,2425.80,2421.00,2438.20,2404.00,2435.00,2434.25,2424.03,421580,1.021924e+14,21932,188670,0.4475,2539.452292
244,2015-12-28,TCS,EQ,2434.25,2428.00,2466.40,2420.20,2456.95,2462.70,2455.00,1852099,4.546896e+14,43390,1060100,0.5724,2539.639792
245,2015-12-29,TCS,EQ,2462.70,2458.35,2465.30,2445.75,2449.35,2455.80,2452.26,854262,2.094875e+14,26975,433986,0.5080,2539.689792
246,2015-12-30,TCS,EQ,2455.80,2453.05,2459.00,2412.30,2421.70,2418.30,2442.06,802881,1.960682e+14,49464,632180,0.7874,2539.298125
247,2015-12-31,TCS,EQ,2418.30,2415.75,2448.50,2407.50,2430.00,2436.85,2428.90,620159,1.506303e+14,42600,400391,0.6456,2538.994583
248,2016-01-01,TCS,EQ,2436.85,2439.00,2439.00,2412.25,2414.10,2416.40,2423.73,356131,8.631649e+13,15545,246115,0.6911,2538.655000

In [10]:
tcsdf=pd.DataFrame(new_tcs)

In [11]:
tcsdf.head()

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2015-01-01,TCS,EQ,2558.25,2567.0,2567.00,2541.00,2550.00,2545.55,2548.51,183415,4.674345e+13,8002,52870,0.2883
1,2015-01-02,TCS,EQ,2545.55,2551.0,2590.95,2550.60,2588.40,2579.45,2568.19,462870,1.188740e+14,27585,309350,0.6683
2,2015-01-05,TCS,EQ,2579.45,2581.0,2599.90,2524.65,2538.10,2540.25,2563.94,877121,2.248886e+14,43234,456728,0.5207
3,2015-01-06,TCS,EQ,2540.25,2529.1,2529.10,2440.00,2450.05,2446.60,2466.90,1211892,2.989615e+14,84503,714306,0.5894
4,2015-01-07,TCS,EQ,2446.60,2470.0,2479.15,2407.45,2426.90,2417.70,2433.96,1318166,3.208362e+14,101741,886368,0.6724

In [14]:
vol = tcsdf['Volume'].index.values.tolist()
volume_shocks =[]
for i in range(1,len(vol)):
    if(tcsdf['Volume'][i]>(tcsdf['Volume'][i-1]+(.1*tcsdf['Volume'][i-1]))):
        volume_shocks.append(1)
    else:
        volume_shocks.append(0)
tcsdf['Volume_shocks']=pd.DataFrame({'Volume Shocks':volume_shocks})
tcsdf.head()

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Volume_shocks
0,2015-01-01,TCS,EQ,2558.25,2567.0,2567.00,2541.00,2550.00,2545.55,2548.51,183415,4.674345e+13,8002,52870,0.2883,1.0
1,2015-01-02,TCS,EQ,2545.55,2551.0,2590.95,2550.60,2588.40,2579.45,2568.19,462870,1.188740e+14,27585,309350,0.6683,1.0
2,2015-01-05,TCS,EQ,2579.45,2581.0,2599.90,2524.65,2538.10,2540.25,2563.94,877121,2.248886e+14,43234,456728,0.5207,1.0
3,2015-01-06,TCS,EQ,2540.25,2529.1,2529.10,2440.00,2450.05,2446.60,2466.90,1211892,2.989615e+14,84503,714306,0.5894,0.0
4,2015-01-07,TCS,EQ,2446.60,2470.0,2479.15,2407.45,2426.90,2417.70,2433.96,1318166,3.208362e+14,101741,886368,0.6724,0.0

In [15]:
closing=tcsdf['Close'].index.tolist()
price_shock=[]
for i in range(0,len(closing)-1):
    if(tcsdf['Close'][i+1]-tcsdf['Close'][i]>(.02*(tcsdf['Close'][i+1]-tcsdf['Close'][i]))):
        price_shock.append(1)
    else:
        price_shock.append(0)
tcsdf['Price_shocks']=pd.DataFrame({'Price_shocks':price_shock})
tcsdf.head()

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Volume_shocks,Price_shocks
0,2015-01-01,TCS,EQ,2558.25,2567.0,2567.00,2541.00,2550.00,2545.55,2548.51,183415,4.674345e+13,8002,52870,0.2883,1.0,1.0
1,2015-01-02,TCS,EQ,2545.55,2551.0,2590.95,2550.60,2588.40,2579.45,2568.19,462870,1.188740e+14,27585,309350,0.6683,1.0,0.0
2,2015-01-05,TCS,EQ,2579.45,2581.0,2599.90,2524.65,2538.10,2540.25,2563.94,877121,2.248886e+14,43234,456728,0.5207,1.0,0.0
3,2015-01-06,TCS,EQ,2540.25,2529.1,2529.10,2440.00,2450.05,2446.60,2466.90,1211892,2.989615e+14,84503,714306,0.5894,0.0,0.0
4,2015-01-07,TCS,EQ,2446.60,2470.0,2479.15,2407.45,2426.90,2417.70,2433.96,1318166,3.208362e+14,101741,886368,0.6724,0.0,1.0

In [16]:
#model testing
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

In [17]:
TCS=tcs.drop(columns=['Symbol','Series'])
TCS.head()

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
Date,,,,,,,,,,,,
2015-01-01,2558.25,2567.0,2567.00,2541.00,2550.00,2545.55,2548.51,183415,4.674345e+13,8002,52870,0.2883
2015-01-02,2545.55,2551.0,2590.95,2550.60,2588.40,2579.45,2568.19,462870,1.188740e+14,27585,309350,0.6683
2015-01-05,2579.45,2581.0,2599.90,2524.65,2538.10,2540.25,2563.94,877121,2.248886e+14,43234,456728,0.5207
2015-01-06,2540.25,2529.1,2529.10,2440.00,2450.05,2446.60,2466.90,1211892,2.989615e+14,84503,714306,0.5894
2015-01-07,2446.60,2470.0,2479.15,2407.45,2426.90,2417.70,2433.96,1318166,3.208362e+14,101741,886368,0.6724

In [18]:
X = TCS.iloc[:, :-1].values
y = TCS.iloc[:, 11].values

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [20]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
#predict the test set results
y_pred = lr.predict(X_test)
y_pred

array([0.6442324 , 0.70254227, 0.75726519, 0.69120863, 0.67659881,
       0.66686676, 0.61358255, 0.702276  , 0.64426375, 0.68376347,
       0.57802883, 0.70864277, 0.68312933, 0.69711496, 0.81858953,
       0.64957701, 0.69321584, 0.61167572, 0.65980851, 0.67206518,
       0.68034175, 0.61177699, 0.6854376 , 0.60375911, 0.58105553,
       0.67243792, 0.62116563, 0.76477819, 0.59932365, 0.67051161,
       0.61470002, 0.59469766, 0.90028763, 0.6066485 , 0.59976823,
       0.6101339 , 0.60625119, 0.60117822, 0.58087006, 0.63671943,
       0.63565508, 0.72805601, 0.82312367, 0.58604967, 0.87167953,
       0.70941619, 0.69332967, 0.48647053, 0.78894801, 0.64306476])

In [22]:
from sklearn.metrics import mean_squared_error
from math import sqrt

rmse = sqrt(mean_squared_error(y_test, y_pred))

from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

adj_r2 = 1 - float(len(y)-1)/(len(y)-len(lr.coef_)-1)*(1 - r2)

rmse, r2, adj_r2,  lr.coef_, lr.intercept_

(0.039615495530660697,
 0.7826322162981821,
 0.772543416210756,
 array([ 2.51569353e-04, -1.27960613e-04, -1.62565321e-03, -2.61669831e-05,
        -6.46830128e-04,  1.25157497e-04,  1.97758179e-03, -4.82938563e-07,
         4.84611266e-16,  6.38981990e-07,  5.75897687e-07]),
 0.8158281740442717)

In [23]:
from sklearn.linear_model import LassoLars
regressor = LassoLars(alpha=0.01)
regressor.fit(X_train,y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([0.67180151, 0.67180151, 0.67180151, 0.67180151, 0.67180151,
       0.67180151, 0.67180151, 0.67180151, 0.67180151, 0.67180151,
       0.67180151, 0.67180151, 0.67180151, 0.67180151, 0.67180151,
       0.67180151, 0.67180151, 0.67180151, 0.67180151, 0.67180151,
       0.67180151, 0.67180151, 0.67180151, 0.67180151, 0.67180151,
       0.67180151, 0.67180151, 0.67180151, 0.67180151, 0.67180151,
       0.67180151, 0.67180151, 0.67180151, 0.67180151, 0.67180151,
       0.67180151, 0.67180151, 0.67180151, 0.67180151, 0.67180151,
       0.67180151, 0.67180151, 0.67180151, 0.67180151, 0.67180151,
       0.67180151, 0.67180151, 0.67180151, 0.67180151, 0.67180151])

In [24]:
#Applying k-Fold Cross Validation

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=regressor,X=X_train,y=y_train,cv=10)
accuracies

array([-9.71024052e-02, -7.43067820e-02, -1.66089055e-01, -2.16622523e-04,
       -4.65182219e-02, -1.16411109e-02, -1.92017153e-03, -2.83810391e-01,
       -1.36492225e-02, -1.09113778e-01])

In [25]:
#ridge
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [26]:
from sklearn.linear_model import Ridge
regressor = Ridge()
regressor.fit(X_train,y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.632747e-28
  overwrite_a=True).T

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [27]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([0.64848798, 0.70155506, 0.75563975, 0.69259275, 0.67738434,
       0.66780259, 0.61673846, 0.70227277, 0.64785658, 0.68583108,
       0.57979747, 0.70939531, 0.68290697, 0.69788805, 0.81871706,
       0.65219806, 0.69312926, 0.61352803, 0.66433647, 0.67385806,
       0.68158742, 0.61367774, 0.68528991, 0.60719771, 0.58193216,
       0.67469045, 0.62118592, 0.76531255, 0.60374376, 0.67156435,
       0.61652562, 0.59736309, 0.89940998, 0.60835127, 0.60066364,
       0.61355422, 0.60797377, 0.60315096, 0.58324869, 0.63711995,
       0.63897776, 0.72940381, 0.82217502, 0.58852491, 0.86835088,
       0.70957294, 0.69707707, 0.4827425 , 0.78653744, 0.64651891,
       0.760418  , 0.7627075 , 0.67025599, 0.70970476, 0.63018782,
       0.58266072, 0.67231146, 0.66321608, 0.67469954, 0.75848076,
       0.62312937, 0.54408276, 0.67716873])

In [28]:
#Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=regressor,X=X_train,y=y_train,cv=10)
accuracies

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.500303e-28
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.332306e-28
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number6.207160e-28
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.171500e-28
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number4.354353e-28
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.742290e-28
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.260652e-28
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.246648e-28
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number5.484873e-28
  overwrite_a=True).T
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:112: LinAlgWarning: scipy.linalg.solve
Ill-conditioned matrix detected. Result is not guaranteed to be accurate.
Reciprocal condition number6.518978e-28
  overwrite_a=True).T

array([0.71202529, 0.80168269, 0.7662954 , 0.74674746, 0.55028131,
       0.83175978, 0.68784051, 0.75703936, 0.75423112, 0.85496728])

In [29]:
def price_shock_wo_vol_shock(stock):
    
    stock["not_vol_shock"]  = ((stock["Volume_shocks"].astype(bool))).astype(int)
    stock["price_shock_w/0_vol_shock"] = stock["not_vol_shock"] & stock["Price_shocks"]
    
    return stock

In [30]:
price_shock_wo_vol_shock(tcsdf)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Volume_shocks,Price_shocks,not_vol_shock,price_shock_w/0_vol_shock
0,2015-01-01,TCS,EQ,2558.25,2567.00,2567.00,2541.00,2550.00,2545.55,2548.51,183415,4.674345e+13,8002,52870,0.2883,1.0,1.0,1,True
1,2015-01-02,TCS,EQ,2545.55,2551.00,2590.95,2550.60,2588.40,2579.45,2568.19,462870,1.188740e+14,27585,309350,0.6683,1.0,0.0,1,False
2,2015-01-05,TCS,EQ,2579.45,2581.00,2599.90,2524.65,2538.10,2540.25,2563.94,877121,2.248886e+14,43234,456728,0.5207,1.0,0.0,1,False
3,2015-01-06,TCS,EQ,2540.25,2529.10,2529.10,2440.00,2450.05,2446.60,2466.90,1211892,2.989615e+14,84503,714306,0.5894,0.0,0.0,0,False
4,2015-01-07,TCS,EQ,2446.60,2470.00,2479.15,2407.45,2426.90,2417.70,2433.96,1318166,3.208362e+14,101741,886368,0.6724,0.0,1.0,0,False
5,2015-01-08,TCS,EQ,2417.70,2442.40,2449.00,2420.55,2446.00,2443.80,2434.81,782704,1.905739e+14,47699,450768,0.5759,1.0,1.0,1,True
6,2015-01-09,TCS,EQ,2443.80,2455.00,2519.90,2450.00,2510.00,2512.30,2490.01,1598821,3.981082e+14,81743,865777,0.5415,0.0,0.0,0,False
7,2015-01-12,TCS,EQ,2512.30,2517.00,2528.00,2480.25,2527.95,2509.70,2497.82,798003,1.993266e+14,58810,451228,0.5654,0.0,0.0,0,False
8,2015-01-13,TCS,EQ,2509.70,2520.00,2530.40,2480.10,2498.00,2497.90,2509.40,734216,1.842440e+14,49993,386133,0.5259,1.0,1.0,1,True
9,2015-01-14,TCS,EQ,2497.90,2516.00,2531.80,2500.50,2525.05,2521.95,2517.54,893548,2.249546e+14,69237,498193,0.5575,1.0,1.0,1,True
10,2015-01-15,TCS,EQ,2521.95,2533.00,2581.75,2523.25,2542.05,2539.10,2550.97,2504960,6.390076e+14,96363,1598846,0.6383,0.0,0.0,0,False
11,2015-01-16,TCS,EQ,2539.10,2543.70,2545.00,2484.30,2526.00,2532.15,2511.39,2646915,6.647444e+14,127847,1372200,0.5184,0.0,0.0,0,False
12,2015-01-19,TCS,EQ,2532.15,2536.00,2551.00,2503.00,2509.00,2511.00,2516.06,567537,1.427954e+14,38860,309156,0.5447,1.0,0.0,1,False
13,2015-01-20,TCS,EQ,2511.00,2520.00,2530.00,2483.25,2498.00,2500.45,2498.94,1029283,2.572121e+14,58066,733487,0.7126,1.0,1.0,1,True
14,2015-01-21,TCS,EQ,2500.45,2522.00,2522.00,2488.25,2518.00,2513.80,2507.75,1155240,2.897055e+14,75976,771316,0.6677,0.0,0.0,0,False
15,2015-01-22,TCS,EQ,2513.80,2516.50,2521.25,2495.50,2511.00,2513.55,2509.31,1056607,2.651355e+14,74837,742399,0.7026,1.0,0.0,1,False
16,2015-01-23,TCS,EQ,2513.55,2514.00,2532.05,2496.10,2504.10,2503.60,2507.34,1575190,3.949530e+14,94619,1205911,0.7656,0.0,0.0,0,False
17,2015-01-27,TCS,EQ,2503.60,2512.35,2515.00,2489.55,2504.20,2502.05,2502.26,1369368,3.426510e+14,71406,1079233,0.7881,1.0,1.0,1,True
18,2015-01-28,TCS,EQ,2502.05,2503.00,2544.90,2502.90,2533.40,2539.60,2529.32,1560990,3.948240e+14,101994,1142166,0.7317,1.0,1.0,1,True
19,2015-01-29,TCS,EQ,2539.60,2538.00,2568.70,2512.90,2560.70,2544.65,2531.88,1867196,4.727520e+14,67497,1547590,0.8288,1.0,0.0,1,False
20,2015-01-30,TCS,EQ,2544.65,2560.70,2575.00,2470.00,2484.00,2482.05,2494.94,2908701,7.257025e+14,119200,2355497,0.8098,0.0,1.0,0,False
21,2015-02-02,TCS,EQ,2482.05,2482.00,2521.45,2462.05,2516.00,2514.20,2500.60,1590901,3.978211e+14,89485,1171718,0.7365,0.0,1.0,0,False
22,2015-02-03,TCS,EQ,2514.20,2511.65,2565.00,2507.10,2552.25,2558.25,2536.23,1172527,2.973793e+14,75106,701449,0.5982,0.0,0.0,0,False
23,2015-02-04,TCS,EQ,2558.25,2568.00,2571.70,2502.10,2514.95,2514.30,2523.08,1122709,2.832687e+14,60615,807091,0.7189,1.0,1.0,1,True
24,2015-02-05,TCS,EQ,2514.30,2520.00,2591.70,2519.00,2553.00,2552.40,2558.13,2265084,5.794386e+14,77935,1638106,0.7232,0.0,1.0,0,False
25,2015-02-06,TCS,EQ,2552.40,2553.00,2594.80,2550.85,2576.10,2575.75,2578.40,1068208,2.754265e+14,82449,582019,0.5449,0.0,0.0,0,False
26,2015-02-09,TCS,EQ,2575.75,2561.50,2569.10,2500.00,2512.00,2512.90,2531.83,1038216,2.628585e+14,72967,695542,0.6699,1.0,0.0,1,False
27,2015-02-10,TCS,EQ,2512.90,2510.00,2526.25,2433.00,2445.50,2441.15,2473.88,1899527,4.699201e+14,114773,1383973,0.7286,0.0,1.0,0,False
28,2015-02-11,TCS,EQ,2441.15,2455.05,2487.25,2447.25,2460.00,2459.90,2468.94,1468761,3.626283e+14,115345,1143243,0.7784,0.0,1.0,0,False
29,2015-02-12,TCS,EQ,2459.90,2479.80,2479.80,2447.00,2469.00,2462.15,2462.56,1553990,3.826787e+14,113845,1269759,0.8171,1.0,1.0,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2015-11-19,TCS,EQ,2351.45,2365.35,2381.60,2352.00,2367.00,2362.55,2366.14,933453,2.208681e+14,55764,632570,0.6777,0.0,1.0,0,False
220,2015-11-20,TCS,EQ,2362.55,2366.50,2423.55,2361.95,2394.50,2398.35,2403.22,1006063,2.417790e+14,60130,575994,0.5725,0.0,0.0,0,False
221,2015-11-23,TCS,EQ,2398.35,2405.30,2413.40,2382.25,2389.30,2391.05,2397.62,544041,1.304405e+14,42359,351815,0.6467,0.0,0.0,0,False
222,2015-11-24,TCS,EQ,2391.05,2380.05,2392.45,2365.50,2366.00,2367.95,2378.62,499320,1.187695e+14,35776,342427,0.6858,1.0,0.0,1,False
223,2015-11-26,TCS,EQ,2367.95,2377.90,2382.40,2337.85,2346.00,2345.55,2355.52,1457646,3.433509e+14,77452,969589,0.6652,0.0,1.0,0,False
224,2015-11-27,TCS,EQ,2345.55,2348.00,2359.45,2332.50,2354.95,2353.35,2348.70,868603,2.040086e+14,62719,518858,0.5973,1.0,1.0,1,True
225,2015-11-30,TCS,EQ,2353.35,2365.00,2391.25,2350.15,2373.55,2364.70,2365.21,2050024,4.848745e+14,85439,1102521,0.5378,0.0,0.0,0,False
226,2015-12-01,TCS,EQ,2364.70,2362.90,2378.05,2357.05,2359.75,2361.90,2363.85,860997,2.035267e+14,51511,672976,0.7816,0.0,1.0,0,False
227,2015-12-02,TCS,EQ,2361.90,2378.00,2378.10,2346.50,2367.00,2365.20,2362.86,820148,1.937896e+14,38694,580713,0.7081,1.0,0.0,1,False
228,2015-12-03,TCS,EQ,2365.20,2360.00,2373.00,2347.00,2350.00,2350.75,2356.59,1141679,2.690468e+14,41715,765969,0.6709,0.0,0.0,0,False
229,2015-12-04,TCS,EQ,2350.75,2340.00,2347.30,2321.10,2330.00,2328.40,2330.08,623046,1.451747e+14,32999,426970,0.6853,1.0,0.0,1,False
230,2015-12-07,TCS,EQ,2328.40,2332.20,2343.90,2315.25,2321.00,2319.80,2322.27,691302,1.605390e+14,52150,487587,0.7053,0.0,1.0,0,False
231,2015-12-08,TCS,EQ,2319.80,2319.40,2349.00,2317.30,2326.25,2329.00,2332.95,569982,1.329739e+14,47957,336913,0.5911,1.0,1.0,1,True
232,2015-12-09,TCS,EQ,2329.00,2337.90,2372.80,2320.00,2370.00,2367.65,2361.23,2641403,6.236954e+14,59592,1365071,0.5168,0.0,1.0,0,False
233,2015-12-10,TCS,EQ,2367.65,2369.00,2391.20,2352.00,2380.95,2384.55,2374.82,861994,2.047084e+14,52429,556996,0.6462,0.0,1.0,0,False
234,2015-12-11,TCS,EQ,2384.55,2383.00,2391.95,2363.25,2383.15,2386.00,2384.13,826189,1.969746e+14,53651,598804,0.7248,1.0,0.0,1,False
235,2015-12-14,TCS,EQ,2386.00,2335.20,2387.00,2330.60,2375.00,2378.45,2364.84,1359266,3.214443e+14,58637,758806,0.5582,0.0,0.0,0,False
236,2015-12-15,TCS,EQ,2378.45,2378.45,2385.00,2363.05,2379.50,2375.85,2375.03,567934,1.348859e+14,52585,421587,0.7423,1.0,1.0,1,True
237,2015-12-16,TCS,EQ,2375.85,2384.00,2414.50,2384.00,2407.50,2408.40,2402.07,717967,1.724609e+14,48074,494205,0.6883,1.0,1.0,1,True
238,2015-12-17,TCS,EQ,2408.40,2415.00,2445.00,2393.35,2434.10,2439.75,2418.57,809422,1.957647e+14,46818,569320,0.7034,1.0,0.0,1,False
239,2015-12-18,TCS,EQ,2439.75,2420.00,2434.20,2400.65,2409.80,2416.80,2416.02,1512485,3.654198e+14,47644,1052042,0.6956,0.0,1.0,0,False
240,2015-12-21,TCS,EQ,2416.80,2419.95,2450.00,2406.85,2443.00,2446.40,2428.40,805052,1.954989e+14,41004,425890,0.5290,0.0,0.0,0,False
241,2015-12-22,TCS,EQ,2446.40,2440.00,2440.00,2400.00,2407.00,2405.05,2413.33,780429,1.883430e+14,30995,476137,0.6101,0.0,1.0,0,False
242,2015-12-23,TCS,EQ,2405.05,2415.00,2435.00,2410.55,2418.80,2425.80,2425.06,424917,1.030449e+14,31057,253475,0.5965,0.0,1.0,0,False
243,2015-12-24,TCS,EQ,2425.80,2421.00,2438.20,2404.00,2435.00,2434.25,2424.03,421580,1.021924e+14,21932,188670,0.4475,1.0,1.0,1,True
244,2015-12-28,TCS,EQ,2434.25,2428.00,2466.40,2420.20,2456.95,2462.70,2455.00,1852099,4.546896e+14,43390,1060100,0.5724,0.0,0.0,0,False
245,2015-12-29,TCS,EQ,2462.70,2458.35,2465.30,2445.75,2449.35,2455.80,2452.26,854262,2.094875e+14,26975,433986,0.5080,0.0,0.0,0,False
246,2015-12-30,TCS,EQ,2455.80,2453.05,2459.00,2412.30,2421.70,2418.30,2442.06,802881,1.960682e+14,49464,632180,0.7874,0.0,1.0,0,False
247,2015-12-31,TCS,EQ,2418.30,2415.75,2448.50,2407.50,2430.00,2436.85,2428.90,620159,1.506303e+14,42600,400391,0.6456,0.0,0.0,0,False
248,2016-01-01,TCS,EQ,2436.85,2439.00,2439.00,2412.25,2414.10,2416.40,2423.73,356131,8.631649e+13,15545,246115,0.6911,NaN,NaN,1,False

In [31]:
import bokeh
from bokeh.plotting import figure, output_file, show
from bokeh.io import show, output_notebook
from bokeh.palettes import Blues9
from bokeh.palettes import RdBu3
from bokeh.models import ColumnDataSource, CategoricalColorMapper, ContinuousColorMapper
from bokeh.palettes import Spectral11

In [32]:
def bokeh_plot(stock):
    data = dict(stock=stock['Close'], Date=stock.index)
    
    p = figure(plot_width=800, plot_height=250)
    p.line(stock.index, stock['Close'], color='blue', alpha=0.5)
    
    #show price shock w/o vol shock
    
    p.circle(stock.index, stock.Close*stock["price_shock_w/0_vol_shock"], size=4, legend='price shock without vol shock')
    show(p)

In [33]:
bokeh_plot(tcsdf)